zaquestion/lab

.gitignore

Adding a gitignore yawls

---

cmd/issueList.go
cmd/mrList.go

[#35] Alias `lab mr ls` to `lab mr list`.

---

cmd/issueCreate.go
cmd/mrCreate.go
internal/gitlab/gitlab.go

Also adds a slight speedup for commands which need to call the gitlab api multiple times
Addresses #29

Support issue/mr templates through a "default.md" tmpl

---

Makefile
cmd/issueCreate_test.go
cmd/mrCreate_test.go
cmd/snippetCreate.go
cmd/snippetCreate_test.go
internal/git/edit.go
internal/git/edit_test.go
testdata/test.git/config
testdata/testfile

- included a small fix to how GIT_EDITOR values were interpreted to closer match git

(tests) add unittests around pkg cmd functions to increase coverage

---

cmd/issue.go
cmd/issueClose.go
cmd/issue_test.go
cmd/mr.go
cmd/mrCheckout.go
cmd/mrClose.go
cmd/mrCreate.go
cmd/mrCreate_test.go
cmd/mrList.go
cmd/mrMerge.go
cmd/mrShow.go
cmd/mr_test.go
cmd/snippet.go
cmd/snippet_test.go
internal/gitlab/gitlab.go

included snippet delete tests as well

(issue,mr) support close subcommand

---

cmd/clone.go
internal/git/edit.go
internal/git/git.go
internal/gitlab/gitlab.go

Before lab had tests these were very useful, at this point I generally only need to add new debug statements when developing new functionality

(debug) remove debug statements

---

.travis.yml
cmd/ciLint_test.go
cmd/clone_test.go
cmd/fork_test.go
cmd/issueCreate_test.go
cmd/issueList_test.go
cmd/issueShow_test.go
cmd/issue_test.go
cmd/mrCheckout_test.go
cmd/mrCreate_test.go
cmd/mrList_test.go
cmd/mrShow_test.go
cmd/mr_test.go
cmd/snippetCreate_test.go
cmd/snippetList_test.go
cmd/snippet_test.go

On my computer this is showing a 4x speedup for the cmd package

(tests) run integration tests in parallel

---

.travis.yml
cmd/project.go
cmd/projectCreate.go
cmd/projectCreate_test.go
cmd/root_test.go
internal/gitlab/gitlab.go

TODO:
- Address todos in code
- Add tests

[#113] Support `lab repo create` for creating a project on gitlab

---

.travis.yml

os.Exit cannot be captured in coverage, not much sense it counting against the coverage calculation

(tests) remove log.Fatal from coverage results

---

Makefile
internal/config/config.go
internal/config/config_test.go
main.go

Also removes the old gitconfig based config and tests the newer lab.hcl
configuration

[#136] (fix) issue displaying token url when entering credentials

---

Gopkg.lock
Gopkg.toml
Makefile
cmd/ci.go
cmd/ciTrace.go
cmd/ciTrace_test.go
cmd/ciView.go
cmd/ciView_test.go
cmd/mrCreate.go
cmd/root.go
cmd/root_test.go
cmd/snippetList.go
internal/git/git.go
internal/gitlab/gitlab.go
testdata/test.git/config

Updates every 5 seconds and displays how long jobs are running. With colors!

[#74] Add (beta) CI Pipeline interface: live view-only

---

Gopkg.lock
main.go

It uses `LAB` as the prefix. To set the host you would do `LAB_CORE_HOST`

allow host, user, and token to be set with environment, implements #155

---

README.md
cmd/issue_list_test.go
cmd/mr_list_test.go

also reposition putting the gif front and center cause its rad and to make it load on the project page on mobile

(tests) make list tests more robust

---

cmd/ci_run.go
cmd/ci_run_test.go
internal/gitlab/gitlab.go

Introducing command to start/run a pipeline. The current implementation uses the current branch/ref and assumes that the remote branch has the same name - this can be changed with additional argument to the command. Also not sure if `run` is the best name for the command, `create` is the verb chosen by gitlab.
This pull request addresses https://github.com/zaquestion/lab/issues/187
First time contributing in this project, so not sure if master is the correct target branch :)

Introducing CI run command to create a pipeline

---

cmd/mr_approve.go
cmd/mr_thumb.go
internal/gitlab/gitlab.go

Support approve and thumb operations on MRs

---

cmd/ci_trace.go
cmd/ci_view.go

This is nicer if you prefer viewing trace logs the way lab ci trace provides them instead of using the tview ui view

(ci view) support suspending application to view trace logs

---

cmd/ci_run.go
cmd/ci_run_test.go
internal/config/config.go
internal/gitlab/gitlab.go
main.go
testdata/test.git/config

This needs some tests pre-merge

Expand on #187 and implement #190, allow ci pipelines to be created/trigger and allow lab to "just work" in gitlab ci

---

cmd/mr_create.go

refactored only one place, so the underscores should be hyphens instead

fix remove source branch and allow collaboration mr create options

---

README.md

I made a donation on Liberapay. Why not adding a badge on the README.md file?
I also add carriage return between the badges. It doesn't changed the rendered markdown but it make the source clearer.

Add liberapay donation link

---

CONTRIBUTING.md
cmd/root.go
cmd/root_test.go

fix failed passthrough to git when using flags on the rootCmd

---

CONTRIBUTING.md
README.md

Just a quick take based on my experience and the discussion in #239.

Document testing procedures

---

install.sh

Prettify install script

---

cmd/ci_run.go
cmd/ci_trace.go
cmd/ci_view.go
cmd/completion_function.go
cmd/issue_browse.go
cmd/issue_close.go
cmd/issue_create.go
cmd/issue_list.go
cmd/issue_note.go
cmd/issue_show.go
cmd/mr_approve.go
cmd/mr_browse.go
cmd/mr_checkout.go
cmd/mr_close.go
cmd/mr_create.go
cmd/mr_list.go
cmd/mr_merge.go
cmd/mr_show.go
cmd/mr_thumb.go
cmd/snippet_browse.go
cmd/snippet_create.go
cmd/snippet_delete.go
cmd/snippet_list.go

`remote` parameter is now completed where available

updated zsh completion for remote parameter

---

cmd/ci_run.go
cmd/ci_trace.go

fix? panic on ci trace

---

README.md

Adds documentation on generating bash and zsh completions.

README: Add completion documentation

---

cmd/mr_rebase.go
internal/gitlab/gitlab.go

Note: untested for now, I'll try to do that later

add `mr rebase`

---

cmd/ci_run.go

Fix spelling error

---

README.md

Never heard of it before arriving here.

README: clarify what HCL is

---

README.md

See: https://pkgs.alpinelinux.org/packages?name=lab&branch=edge
Note: The package is available only on edge branch for now.

docs: apline installation usage

---

go.mod
go.sum

fixed deprecation notice in latest elvish version

updated carapace to 0.0.16

---

cmd/issue_show.go
cmd/mr_show.go
go.mod
go.sum

Implement on-demand and automatic new comment detection on MRs and Issues.
P.

show mr and show issue automatic highlight logging

---

cmd/mr_checkout.go

despite accepting the remote as an arg and looking up the MRs on the correct project, fetchs were still being done on the forkedFromRemote when they should also have been carried out on the override

fix: (mr checkout) override target remote when passed as arg

---

cmd/issue_edit.go

issue_edit: Fix minor typo

---

cmd/ci_view_test.go
cmd/mr_show.go
internal/action/action.go
internal/config/config.go
internal/git/edit.go
internal/git/git.go
internal/git/git_test.go
internal/gitlab/gitlab.go

Cleaned up various lint errors from golint

refactor: golint cleanup

---

cmd/mr_test.go

I did not add much new testing with https://github.com/zaquestion/lab/pull/460.  I need to add tests for updating MRs and MR comments.

mr edit testing

---

cmd/issue_show.go
cmd/issue_show_test.go
cmd/mr_show.go
cmd/mr_show_test.go
internal/gitlab/gitlab.go

GitLab has functionality to display the relationship between Merge Requests and Issues.
Display the relationship status in 'lab mr show' and 'lab issue show' commands.

show: relate issue and mr

---

cmd/mr_list_test.go
cmd/mr_show_test.go

https://gitlab.com/zaquestion/test/-/merge_requests/14 was dropped
somehow.  Repush to MR 17.

lab: Fix 'mr show' tests

---

internal/gitlab/gitlab.go

When doing 'lab mr show <mr_id>' I noticed that some comments visible in
the UI were missing from the command output.  This happens because
MRListDiscussions is currently only returning the first page of results.
Update MRListDiscussions to output discussions of all the pages of
results.

gitlab: MRListDiscussions must return all discussions

---

cmd/ci_status_test.go
cmd/mr_test.go

Addresses review comments raised in https://github.com/zaquestion/lab/pull/515
after the PR was merged.

Some changes to upstream-branch tests

---

cmd/mr_list_test.go
cmd/mr_reopen.go
cmd/mr_reopen_test.go
internal/gitlab/gitlab.go

mr_reopen: add command for reopening a closed MR

---

cmd/mr_list_test.go

Update the latest MR name to which mr_list_test checks.

mr_list: fix latest updated MR test

---

cmd/ci_view.go

After the tcell/v2 update, any key press during `lab ci view` results
in a lock up. It is unclear whether the changes in input handling on
the tcell side are intentional, but we can address the issue by making
the channel that notifies about input events asynchronous and ensure
that we don't overrun its queue.
Fixes #538

ci_view: Fix screen freeze

---

cmd/issue_note.go
cmd/mr_edit.go
cmd/mr_test.go
cmd/util.go

If no MR ID is specified on the command line, the mr subcommands fall
back to looking for a MR associated with the current branch. Extend
that behavior to also try a branch name specified on the command line,
as branch names are usually easier to remember than MR numbers.

util: Support getting MR ID from branch name

---

cmd/issue_show_test.go

I managed to mess up tests ... again /o\

tests: Adjust expected `issue show` output

---

cmd/mr_list.go

Add `--conflicts` and `--no-conflicts` flags to `lab mr list`, so the user can retrieve specific MRs based on their merge status.

mr_list: add flags for checking merge conflicts

---

internal/config/config.go

It's attempting not attemping.

config: Fix "attemping" typo

---

cmd/mr_approve_test.go

This is failing for some reason.

mr approve: Fix unapprove test failures

---

internal/gitlab/gitlab.go

Some times the ImportStatus API call seems to file (I've seen it happen a couple of times in our testing).
This patch make sure we handle the error correctly and not interrupt the fork process.
Fixes #589

gitlab: fix error handling for ImportStatus check

---

internal/gitlab/gitlab.go

This MR create additional checking steps to make sure the user isn't trying to fork a project that, somehow, conflicts with other projects already on his "destination" namespace.
Some of the checkings might be confusing, a more detailed explanation can be seen in the commit log.
But keep in mind the code I'm changing is related to the process of finding **another fork** where the user wants the new one to land. At the same time, 1) the user can set a **custom** name, namespace and path and 2) the project may have been redirected (`target.PathWithNamespace` can be different from `namespace+name` passed by the user).

gitlab: improve checking for project lookup during fork

---

cmd/issue_list.go
cmd/mr_list.go

The option `--mine` in `lab mr list`, both to me and others, is kinda misleading since it gives the impression of "I'm the author of that". This patchset removes it from mr_list and adds the `--author` for both mr_list and issue_list.
Fixes #617 .

add `author` filter and remove `mine` from lists

---

cmd/issue_create.go
cmd/issue_edit.go
cmd/issue_list.go
cmd/mr_create.go
cmd/mr_edit.go
cmd/mr_list.go
internal/action/label.go

Works fine with the default remote but i am not too sure about the remote arg parsing with `parseArgsRemoteAndProject` (works fine with a fork so i assume it's correct).
[Cache](https://rsteube.github.io/carapace/carapace/cache.html) is written to `/tmp/carapace/{user}/lab/`

added label completion

---

cmd/mr_test.go

This was noticed while implementing the --source option in 'mr create'.
The prepare function in the merge request test code has an error that is
commented out.  This is because the code no longer works correctly and
always throws an error.  The prepare function attempts to clean up any
existing test merge requests prior to creating new ones.
Fix and generalize the prepare test function.

Fix mr test prepare

---

cmd/edit_common.go
cmd/issue_create.go
cmd/issue_edit.go
cmd/mr_create.go
cmd/mr_edit.go
cmd/util.go
internal/gitlab/gitlab.go

Add an option to add and remove reviewers from 'mr edit' and 'mr create'.  This involves generalizing and moving some code around.  I've also added the ability to add and remove reviewers and assignees via user's email addresses.
Closes: #639 

Add reviewers

---

cmd/mr_test.go

Fix test failures in cmd/mr_test.go

Update mr_test.go to fix test failure case

---

cmd/fork_test.go
cmd/mr_list_test.go
cmd/mr_test.go

Add tests for
lab mr edit --approve
lab mr edit --unapprove
lab mr edit --review
lab mr edit --unreview

mr_test: Add tests for assign and review

---

.gitlab-ci.yml
cmd/ci_status_test.go
cmd/root_test.go
cmd/todo_issue.go
internal/config/config.go

lab: Add support for GitLab Testing

---

cmd/todo_list.go

Add a "draft" status and output the title for 'lab todo list --pretty' output.

todo list: Add "draft" status and output the title for --pretty

---

README.md
cmd/completion.go

- also add oil to completion command
related #678

fix copy&paste error in readme

---

internal/logger/logger.go
internal/logger/logger_test.go

This MR adds some testing code for our custom/internal logger and also fix some issues found by the tests.

Fix logging functions and add tests

---

cmd/todo_issue.go
go.mod
go.sum
internal/gitlab/gitlab.go

Added missing link between go-gitlab and lab todo issue to make it
functional.

cmd/lab_todo: Finalized lab todo issue, updated go-gitlab

---

cmd/edit_common.go
internal/gitlab/gitlab.go

Changed os.Open() to ioutil.ReadFile() so we can be consisted on file reads.

Standardize file read

---

cmd/todo_issue.go
cmd/todo_mr.go
cmd/todo_test.go

Add the ability to select a remote and add tests for the todo functions.

todo: Add remote selection and tests

---

README.md

Add an example lab.toml file.
Fix: 805

README.md: Add lab.toml example

---

cmd/mr_discussion_test.go

mr_discussion_test: Add tests for commit comments
Add test for commenting on commits.

Commit comment tests

---

cmd/util.go

Default command flag values can be overriden by setting it on lab's
configuration file and since multiple configuration files are allowed
sometimes the mix of flags can be quite confusing. To help with it this
patch adds the print of all enabled flags when the user calls a command
with --debug enabled (the 'debug' flag itself is ignored though).

util: print command flags enabled when on --debug

---

internal/config/config.go

From GitLab:
"The ability to create personal access tokens without expiry was deprecated in GitLab 15.4 and removed in GitLab 16.0. In GitLab 16.0 and later, existing personal access tokens without an expiry date are automatically given an expiry date of 365 days later than the current date. The automatic adding of an expiry date occurs on GitLab.com during the 16.0 milestone. The automatic adding of an expiry date occurs on self-managed instances when they are upgraded to GitLab 16.0. This change is a breaking change."
Frequent users of GitLab are being caught by this 1-year expiration, and are seeing general command errors, for example,
[prarit@prarit centos-stream-9]$ lab mr show 123
2023/05/20 08:34:51 ERROR: mr_show.go:45: GET …

cmd/root.go: Add config verification

---

cmd/ci_lint.go
cmd/mr_edit.go
internal/gitlab/gitlab.go
internal/gitlab/gitlab_test.go

This fixes a number of tests and code related to breaking changes in GL 16.

fix(ci): Updated tests/code for Gitlab 16.0

---

internal/config/config.go

82444bfa9c07 ("config: Add config verification") added some simple checking to see if a user's token was valid.  After the recent go module updates we can now use the PersonalAccessToken service from go-gitlab to warn a user that their token is about to expire.  This warning should happen once a day when the config is verified.
Warn a user when their token is going to expire within two weeks.

internal/config/config.go: Warn on expiring tokens

---

cmd/issue_list.go
cmd/issue_list_test.go
cmd/mr_list.go
cmd/mr_list_test.go
cmd/mr_show_test.go
cmd/mr_test.go

- add `issue/mr list --milestone=any/none`
- add `issue/mr list --assignee=any/none`
- add `mr list --approver=...`
- add `issue/mr list --reviewer=any/none`
- add tests for all of the above, and then some

Update list commands

---

cmd/mr_list_test.go
cmd/mr_note_test.go

fix the automated tests
