cmd/mergeRequest.go
`lab mr` was originally added because cobra does not implicitly
support commands with `-`'s in them and it was believed that `hub pr`
and hub `pull-request` were aliases. It is now understood that these
are seperate commands. This change corrects the mistake by renaming the
mr command.
=> Rename mr -> merge-request

cmd/mergeRequest.go, cmd/mr.go, cmd/mrCheckout.go, cmd/mrCreate.go, cmd/mrList.go, internal/gitlab/gitlab.go
Implementing these in an attempt to follow the ideas presented here:
https://github.com/github/hub/issues/1536
Honestly, not sure how I feel about these changes. Some considerations:
- `lab mr checkout` could be `lab checkout` with some special cases to
determine if it should checkout the ref
- Aliasing `lab mr` and `lab merge-request`
- `lab mr list` feels better as `lab list mrs`
Following for edit
- `lab edit mr`
- `lab edit issue`
=> Add `lab mr` commands checkout, list, create

cmd/clone.go, cmd/fork.go, cmd/mergeRequest.go, cmd/mrCheckout.go, cmd/mrCreate.go, cmd/mrList.go, internal/git/git.go
(clone) support "upstream"
(fork) fork and clone to "upstream"
(mr) support "upstream"
- list
- checkout
- create
=> Implement #15; support for "upstream" remotes

.goreleaser.yml, .travis.yml
This automates compilation of binary releases and update of Homebrew formula through [goreleaser](https://goreleaser.com/). When you push tag on master branch, Travis will pickup the commit and run the `deploy` phase. This invokes goreleaser, which:
- Builds binaries for Linux and macOS (both 32- and 64-bit builds)
- Creates GitHub release with changelog and binaries (see example: https://github.com/jnv/lab/releases/tag/v0.5.1)
- Updates formula in tap repository (see here: https://github.com/jnv/homebrew-tap/commit/9a4a4400fc073247e92616586f9f5352af6ed7e3)
Unfortunately there are currently no options to create formula with build recipes and the original formula is overriden completely.
**ACTION NEEDED**: You will need to add secret environment variable `GITHUB_TOKEN` with `public_repo` …
=> Add goreleaser with CI process

cmd/clone_test.go, cmd/fork_test.go, cmd/root_test.go, internal/gitlab/gitlab.go
Largely part of an effort to improve coverage
=> (tests) Tests for cmd/root, cmd/clone, and cmd/fork

cmd/clone.go, cmd/clone_test.go, cmd/fork.go, internal/git/git.go, main.go
- when adding the upstream remote well run the command from the directory instead of changing to the directory to run the command for now on. This is probably how I should have done it the first time, that logic is written by someone who doesnt use the "upstream" paradigm
=> (tests,fix) coverage for clone test was getting trapped inside the repo dir

Gopkg.lock, Gopkg.toml, cmd/issueList_test.go, cmd/issueShow.go, cmd/issueShow_test.go, cmd/mrList_test.go, cmd/mrShow.go, cmd/mrShow_test.go
secondarily use gitlab a issue and mr that cover of the show commands
NOTE: Blocked on: https://github.com/xanzy/go-gitlab/pull/294
=> (mr,issue) update show all assignees on issues

cmd/snippet.go, cmd/snippetCreate_test.go, internal/git/edit.go, internal/git/git.go, internal/git/git_test.go
before this would just cause a fatal error indicating "not a git repository"
=> [#98] (snippet,fix) use /tmp for personal snippets when editing outside of a git repo

Makefile, cmd/snippetCreate.go, cmd/snippetCreate_test.go
In practice its largely been confusing. Instead `-m` will be the sole way
for setting title/description and title will default to `-` when not
provided
=> [#99] (snippet) remove editor workflow for writing title/description

cmd/snippet.go, cmd/snippetCreate.go, cmd/snippetCreate_test.go, cmd/snippetList_test.go, cmd/snippet_test.go, internal/git/edit.go
This is better than just checking if its a global snippet since it works for project and personal snippets. It also forces snippets created from scratch (editor workflow) to explicitly use `lab snippet create`
=> (snippet) check for input on standard in when deciding to create a snippet with `lab snippet`

cmd/mrCheckout.go, cmd/mrCheckout_test.go
Similar to convention for `git checkout -b`.
```
-b <branch>           create and checkout a new branch
```
Though in this case, we are cheching out a remote branch with the name
<branch>. Without this flag set, we use the remote branch name as
before.
=> Add lab mr checkout <mrID> -b for naming branch.

Gopkg.lock, cmd/clone.go, cmd/root.go, cmd/snippet_test.go
lab should be wrapping git help functionality and only showing its on when appropriate. The bulk of these changes address the challenges in doing so
=> [#107] (bug) align lab help functionality with git help and --help

internal/git/git.go, internal/git/git_test.go, testdata/test.git/config
This should resolve most issues with using non scp style ssh urls (e.g. git@gitlab.com:user/repo) with lab
=> [#12] (internal/git) support parsing remotes using http/s, ssh://, and git://

cmd/mrCheckout.go, internal/gitlab/gitlab.go
Works as follows:
```
lab mr checkout -t !mrID
```
When `-t` or `--track` is specified the following happens.
- Check for remote by the username if the MR author
- If the remote does not exist, add it as `mr.Author.Username
- Instead of fetching to the configured branch, fetch to `refs/remotes/mr.Author.Username/mr.sourceBranch` (`fetchToRef`)
- Create a local branch starting from `fetchToRef`
- Checkout that branch
Test on the way.
Closes #104
=> [#104] Support setting the remote during `lab mr checkout`

internal/git/git.go, internal/git/git_test.go, testdata/test.git/config
This adds support for GitLab subgroups, i.e. remote URLs like `git@gitlab.com:c137/rick/sanchez/schmeckle.git`
I also took a chance to fix what seemed to be a copy-paste issue in tests.
=> Add support for GitLab subgroups

cmd/root.go
=> fix: prevent `lab create` from being passed through to hub

README.md
This PR adds a link to a .gif file showing how to make use of `lab` starting from a terminal without lab installed. The gif demonstrates the following actions:
1. Install lab
2. Clone the test repo
3. Fork the repo
4. Make a change
5. MR that change
6. Look at the resulting CI pipelines
-----
Please note that currently the gif in question is hosted on my personal website. I encourage the maintainers of this repo to, at some point, archive this gif and it's associated files and then change README.md to point to that archived gif. However, it is left as an exercise for the reader.
=> Add usage gif to README.md

main.go
Hello @zaquestion 
Continuing #155, even after setting the required env (LAB_CORE_HOST, LAB_CORE_USER, LAB_CORE_TOKEN), lab still asks to create the config file if it's not present.
So this pull request handles if no config file is present but the config is in env, then it wont asks user to input the config from stdin, but return the values from env instead.
And `viper.AllSettings()` seems to not return config from env, hence this pr checks for env and return the config asap
=> load config from file only if env is not present

Makefile, cmd/issue_create.go, cmd/mr_create.go, cmd/snippet_create.go, cmd/version.go, docs/lab_issue_create.md, docs/lab_merge-request.md, docs/lab_mr_create.md, docs/lab_snippet.md, docs/lab_snippet_create.md, internal/gitlab/gitlab.go
goreportcard (https://goreportcard.com/report/github.com/zaquestion/lab)
reports a few minor issues with lab, including a misspelling of
"separate" in several locations. This PR fixes that, and also adds a
documentation comment that was reported missing.
Imports whose package names do not match the basename of their import
path (e.g., go-gitlab, go-gitconfig) have had their package names
explicitly rendered by goimports, to more clearly identify the package
name being imported.
=> Fix misspellings and add doc comment

Makefile
Here are a couple things I fixed up while messing around building this on my own systems and [packaging it for ArchLinux](https://aur.archlinux.org/packages/lab). Golang projects are actually a pain in the butt to package because they are so adamant about doing everything themselves (downloading sources, verifying checksums, building form only verified remote paths, etc.) that it's hard to get a package manager wrapped around them. The more bits of the process have standard `make` or similar wrappers the better, and splitting these dependencies so they can be run at the corresponding time in the package process would be better than the monolithic approach.
=> Touchup makefile

cmd/fork_test.go, cmd/issue_list.go, cmd/mr_checkout.go, cmd/mr_list.go, cmd/project_list.go, cmd/project_list_test.go, cmd/root.go, cmd/snippet_list.go, internal/git/git.go, internal/gitlab/gitlab.go
Users can either use `-a` to fetch all results or `-n` to specify a number of results
=> (listing) abstract pagination from user

Gopkg.lock, cmd/mr_list.go, cmd/mr_list_test.go, cmd/project_create.go
This introduces a feature for `mr list`, where users can filter the list of printed merge requests by target branch.
=> Allow filtering by target branch

Gopkg.lock, cmd/mr_browse.go, cmd/mr_browse_test.go
This is a work in progress.
The current code fails with the following error:
```
../../go/src/github.com/zaquestion/lab/cmd/mr_browse.go:46:17: unknown field 'SourceBranch' in struct literal of type "github.com/zaquestion/lab/vendor/github.com/xanzy/go-gitlab".ListProjectMergeRequestsOptions
```
There is indeed a `ListProjectMergeRequestsOptions.SourceBranch` here: https://github.com/xanzy/go-gitlab/blob/master/merge_requests.go#L262
Unfortunately, I have a different file in `vi vendor/github.com/xanzy/go-gitlab/merge_requests.go`...
=> Open the current merge request with lab mr b

cmd/issue_note.go, cmd/issue_note_test.go, internal/git/edit.go, internal/gitlab/gitlab.go
See #68. This adds a very simple `lab issue note` command. It's my first time wrting
Go, so I'm very open to suggestions or corrections. I refactored some of the code in internal/git/edit.go to support this, and most of the code is copied from issue_create.go and issue_browse.go.
If this looks OK, I'd be happy to add `lab snippet note` and possibly `lab mr note` (#83).
As far as I can tell, the tests are still passing. I had trouble getting `make test` to work, but I was able to get things setup so that testing individual files seems to work:
```sh
$ cd cmd/                                                 
$ go test -run Test_issueCreateNote                     
PASS
ok      github.com/zaquestion/lab/cmd   3.373s
$ cd ../internal/git                                    
$ go test -run …
```
=> add `lab issue note` command

cmd/issue_list.go, cmd/issue_list_test.go, cmd/root.go, cmd/root_test.go
Adds search feature to `lab issue list`. (See #208)  Also aliases `list` to `search`, as in `lab project list`. 
```
lab issue list                        # no change; list all open issues
lab issue list "search terms"         # search issues for "search terms"
lab issue search "search terms"       # ditto
lab issue list remote "search terms"  # search "remote" for issues with "search terms"
```
Also, hope its OK I took the liberty to rename the `parseArgs*` functions to make them a little more clear.
=> Issue list search

cmd/issue_edit.go
#245 landed just after #252, so it missed the completion party. I think that this adds the required code to enable positional completion of `[remote]` and `<id>`. @rsteube can you take a peek to make sure I'm doing it right? I ~~copi~~...based this off of the completions in `issue note`.
Thanks!
=> add positional completion to issue edit

cmd/project_create.go
Based on #250, I removed the verbiage from the help text about visibility and left in the `--internal` flag to do the explaining for us. While I was at it, I made `--internal` an actual flag b/c I was worried that someone might (mistakenly) try to use `--internal --public`. In the case of multiple visibility flags, the command with use the "most private" of those provided.
=> project create: update help text

install.sh
Started looking at this script to fix #262, and fixed a few other things while there :)
installing to a custom location is now done by setting the environment variable `PREFIX` before executing the script; eg.:
```bash
PREFIX=/usr install.sh
```
or
```bash
PREFIX=~/.local install.sh
```
=> install.sh script fixes

internal/gitlab/gitlab.go
=> issue comments: implement pagination & show all comments

main.go
Let the HOME environment variable override the path where we look for config
files and check the information in the user database only if not set.
=> (config) Check $HOME before looking up in the user db

cmd/label.go, cmd/label_list.go, cmd/label_list_test.go, internal/gitlab/gitlab.go
Nothing fancy, but I've had this kicking around for a while and might as well see if it sticks. This adds the ability to list and search labels such as:
```
lab label list
lab label search "search term"
```
=> Add `lab label` for listing and searching labels.

LICENSE, README.md
Switching to CC0 should allow lab to be included as a Debian package.
This work has been performed on behalf of the project maintainer, with
permission granted
(https://github.com/zaquestion/lab/issues/294#issuecomment-483877075).
Full discussion at https://github.com/zaquestion/lab/issues/294.
=> Switch from Unlicense to Creative Commons CC0 1.0 license

.goreleaser.yml
https://github.com/zaquestion/lab/issues/291 reports that "brew test" hangs
indefintely for lab. This is because a new lab is built and then, when
executed, it prompts the user for configuration. Standard output is captured by
the brew test runtime environment, so this is not clear for a casual observer.
Ideally, passthrough commands that are serviced by git (or hub) ought not to
stop the world and demand configuration, as well as commands that do not
require access to a GitLab API (e.g., "version"). However, this may require
non-negligible work for minimal gain, and the issue at hand can be avoided by
providing lab with some dummy configuration values passed through the
environment.
In addition, the "git config" lines in the test script have been removed, in
line with comments in the …
=> Stop "brew test" from hanging

cmd/mr_note.go, cmd/mr_note_test.go, internal/gitlab/gitlab.go
Note that this only supports notes and not discussions. There is a lofty set of ideal criteria for this in #83 including the ability to have flags for line numbers. This doesn't support that, but I think this provides a good starting point and additional flags can be added in subsequent feature requests.
`lab mr note <mr_id> -m <message>`
I wrote a test...but I'm not positive how well it is going to work. I largely mirrored the issue note test. I have run this manually and it does work so hopefully the test matches that.
=> Add support for posting notes to Merge Requests.

cmd/issue_browse.go
Lab crashes due to loading a non existed config file for the host url. Since other commands work just fine without the config file, we can use similar approach for `issue browse` command, which is detect project url from git host and build up the url.
=> Fix crash when opening issue in browser

main.go
This makes it easy for distributors to provide completion out of the box in packaged versions of lab
=> #321: allow completions to be generated without authenticating with GitLab

internal/gitlab/gitlab.go, main.go
Also quick fix to skip user lookup when set to avoid the net call
=> Set TLS skip verify when getting user

cmd/issue_create.go, cmd/issue_create_test.go, cmd/issue_edit.go, cmd/issue_show_test.go, cmd/issue_test.go, cmd/mr_browse.go, cmd/mr_create.go, cmd/mr_list.go, cmd/mr_show_test.go, go.mod, go.sum, internal/gitlab/gitlab.go
Fixes https://github.com/zaquestion/lab/issues/349
Required updating the go-gitlab package to a version that supports AssigneeIDs (plural) for MR creation.
Updating go-gitlab in turn required two other changes:
* updating several other functions to pass a pointer to a `gitlab.Labels` instead of a raw `gitlab.Labels`
* updating tests to use the new `https://gitlab.com/zaquestion/test/-/merge_requests/1` style URLs (`-` in the middle).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaquestion/lab/372)
=> Allow specifying multiple assignees when creating an MR

README.md
When building with go 1.12 you will receive the following error:
internal/gitlab/gitlab.go:65:4: unknown field 'ForceAttemptHTTP2' in struct literal of type http.Transport
internal/gitlab/gitlab.go:100:4: unknown field 'ForceAttemptHTTP2' in struct literal of type http.Transport
note: module requires Go 1.13
Makefile:5: recipe for target 'build' failed
make: *** [build] Error 2
Signed-off-by: Jason Wessel <jason.wessel@windriver.com>
=> README.md: Update to require go 13 or newer

README.md
the aliasing is very dangerous, it can kill your terminal:
the problem is that my shell prompt executes git commands to draw prompt. yet lab is pretty aggressive about it's configuration. maybe it's problem on it's own that it should ask for gitlab credentials ONLY when these are needed, proxying things if they are missing.
I've debugged and found the command that my prompt used to be:
```
[~/scm/tmp/castnow (master)★] ➔ alias git='_git() { echo >&2 "git $*"; git "$@"; }; _git'
[~/scm/tmp/castnow (master)★] ➔ cd .
git rev-parse @
[~/scm/tmp/castnow (master)★] ➔
```
```
[~/scm/tmp/castnow (master)★] ➔ lab rev-parse @
Enter GitLab host (default: https://gitlab.com): ^C
```
=> readme: warn before aliasing

cmd/ci_status.go, cmd/ci_trace.go, cmd/ci_view.go, cmd/mr_create.go, cmd/root.go, cmd/root_test.go, internal/gitlab/gitlab.go, internal/gitlab/gitlab_test.go
For issue https://github.com/zaquestion/lab/issues/338
- use of `sha` instead of `ref/branchName` https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines is more correct with detached pipelines ( via `only: merge_requests` )
- use `sha` of upstream (not local)
- add `GetBranch` and remove/replace `BranchPushed`  
- `cmd` parse args unification
- use `parseArgsRemoteString`
- add `parseArgsRemoteRef` (helper)
=> base changes for issue #338

cmd/fork.go
The ability to skip the clone is needed, for the work flow where you
already have a clone of the origin version and you are deciding to
push a new branch or change to your local repository.  It is
especially useful if you have shallow cloned or cloned only a single
branch out of a large repo.
Signed-off-by: Jason Wessel <jason.wessel@windriver.com>
=> fork: Add option to skip the clone

.goreleaser.yml
It would be nice to have arm/arm64 binaries created by goreleaser on next release.
=> .goreleaser.yml: Create arm/arm64 binaries

README.md
Simply invoking the powershell completion script should normally work as well, but somehow subcommands/arguments aren't completed (uses file completion). The Get-Content / Out-String / Invoke-Expression way works as intenden.
=> WIP: added completions to readme

internal/git/edit.go
The command 'lab mr note <id>' fails when the GIT_EDITOR variable contains
single quotes.  For example, if GIT_EDITOR is 'vim -c 'set tw=74' -c 'set
noai' -c 'set wrap' the 'lab mr note' command attempts to open 4 different
files (tw=74, noai, wrap, and MR_NOTE_EDITMSG).  If the single quotes
are replaced by double quotes the 'lab mr note' command completes as
expected; only MR_NOTE_EDITMSG is modified.
Replace single quotes in the GIT_EDITOR environment variable with double
quotes.
=> edit: Fix GIT_EDITOR evaluation

cmd/mr_show.go
If a merge request is unassigned 'mr show' panics [1] because the
mr.Assignee field is nil.
Check mr.Assignee for nil prior to dereferencing it's memory.
Fixes: b0b8ee22492b ("alec/multiple-assignees")
Resolves #389
Cc: Alec Benzer <alec@level.com>
[1] trace of 'mr show':
[prarit@prarit kernel-test]$ ~/git-kernel/github/lab/lab mr show 9
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4d259a]
cmd.printMR
/home/prarit/git-kernel/github/lab/cmd/mr_show.go:50
cmd.func30
/home/prarit/git-kernel/github/lab/cmd/mr_show.go:37
github.x2ecom..z2fspf13..z2fcobra.Command.execute
/home/prarit/go/pkg/mod/github.com/rsteube/cobra@v0.0.1-zsh-comp …
=> mr show: Fix 'mr show' for unassigned Merge Requests

cmd/mr_show.go, cmd/mr_show_test.go, internal/gitlab/gitlab.go
The 'issue show' command has a --comments flag to show all the comments
on an issue.  The same command is useful for the merge request command
'mr show'.
Add a --comments flag to 'mr show' that displays all the comments made
on a merge request.
Minor fix: Also fix a typo with the mr no-markdown flag.
=> lab: Add --comments flag to 'mr show'

cmd/mr_create.go
The default branch on gitlab projects can be changed from master to other
values.  The 'mr create' command defaults to 'master' and should use the
project's default branch instead.
Use the project's default branch instead of 'master'.
=> mr create: Set default target branch

cmd/mr_note.go, cmd/mr_note_test.go
Add the ability to update a merge request with the contents of a file.
This is especially useful when copying in testing contents and/or
boot logs.
Add mr note --file option which takes the location of the file containing
the text as an argument.
=> note: Add mr note --file option

cmd/mr_create.go, cmd/mr_test.go
Add the ability to create a merge request with the contents of a file.
This is especially useful when creating a merge request with testing
contents and/or boot logs.
Add mr create --file option which takes the location of the file containing
the text as an argument.  The first line of the file is interpreted as
the title of the merge request, and the remaining text is the body for
the description of the merge request.
=> mr create: Add mr create --file option

cmd/mr_list.go, cmd/mr_list_test.go, internal/gitlab/gitlab.go
On large projects it would be nice to find my merge requests or
someone else's merge requests.  While coding I came across this
old patchset from Alex Kalderimis and I have simply rebased it
to top-of-tree and squashed his two commits together.
Original commit message from Alex:
"Fixes #249, allowing MRs to be listed by assignee
This adds two new flags to the MR list command:
* --mine: list only MRs assigned to me
* --assignee=username: list only MRs assigned to a particular user"
Developed-by: Alex Kalderimis <alex.kalderimis@gmail.com>
Tested-by: Prarit Bhargava <prarit@redhat.com>
=> mr list: Add --mine and --assignee options

main.go
lab commit 1285411b8584 attempted to fix the missing core.user entry in
~/.config/lab.hcl, however, it seems to have caused more problems than
it fixed [1].
I'm reworking the config code and have noticed several other odd issues so
reverting this isn't a major step backward.
Reported-by: Bruno Meneguele <bmeneg@redhat.com>
[1] https://github.com/zaquestion/lab/issues/411
=> Revert commit 1285411b8584 ("config: Fix missing core.user entry")

cmd/mr_show.go, cmd/mr_show_test.go, internal/git/git.go
Fixes #277 which requests functionality that provides the patches
for an MR in 'git show' format.  This is useful for users that want
to quickly look at a patchset without checking out a branch.
The original patch provided by Eric required users to provide the
target remote, even if the target remote was "origin".  The additional
code provided by Prarit uses the fetch remote name in 'git remote -v'
by default unless the user specifies a specific remote.
Original patch from Eric, with modifications to automatically find the
target remote by Prarit.
Add '--patch' option to 'mr show' that displays the patches for a merge
request in 'git show' format.
Co-Developed-by: Eric Engestrom <eric.engestrom@intel.com>
=> [PATCH] Add `--patch` option to `mr show`

.travis.yml, README.md, cmd/issue_show.go, cmd/mr_show.go, cmd/root_test.go, cmd/snippet_browse_test.go, internal/config/config.go, internal/config/config_test.go, internal/gitlab/gitlab_test.go, main.go, testdata/lab.hcl, testdata/lab.toml
=> New config layout

README.md, cmd/issue_show.go, cmd/mr_show.go
Add a local "comments" config option that always sets "--comments" for the mr and issue show commands.
=> Mr show config comment

internal/config/config.go
Just a small cleanup of the LoadConfig() code.  The two return statements
can be simplified to a single return.
=> config: Small LoadConfig() cleanup

main.go
Resolves issue #374 by skipping config initialization for `--version` and `--help` options passed directly to `lab` command.
=> main: skip config initialization for --version and --help

cmd/clone.go
Solves issue #426 that uses project's name instead of project's path as the directory name.
=> clone: fix folder name used for operations after clonning

cmd/fork.go
Solves issue #424 by considering (sub)group naming when clonning a project after a fork.
=> fork: fix clonning for projects within subgroups

cmd/issue.go, cmd/mr.go
Resolves issue #422 that reports confusion in the -M|--no-markdown flag usage in parent commands.
=> issue,mr: remove markdown flag from parent command

cmd/issue_show.go, cmd/mr_show.go, internal/config/config.go
Move and generalize the show commands' git work tree config file code to
the config code.  The move allows any command to initialize and use a
work tree config file.
Suggested by: Zaq? Wiedmann <zaquestion@gmail.com>
=> config: Add WorkTree functions

cmd/issue_create.go, cmd/issue_edit.go, cmd/issue_note.go, cmd/mr_create.go, cmd/mr_note.go, cmd/util.go, cmd/util_test.go
FIXME: needs testing fixes
FIXME: needs better option and text
The default gitlab formatting will mangle some types of text by default.
For example, if the text entered as the Description contains
This is sentence one and should not be
On the same line as sentence two
then gitlab would merge these lines together as
This is sentence one and should not be On the same line as sentence two.
To fix this add an option to replace line breaks, "\n", with "  \n" [1]
[1] https://gist.github.com/shaunlebron/746476e6e7a4d698b373.
=> lab: Add --force-linebreak option

cmd/mr_discussion.go, cmd/mr_discussion_test.go, internal/gitlab/gitlab.go
This adds the ability to create threads on a Merge Request. It's basically a clone of the note command but talks to the Discussions API instead.
It's very simple but can be expanded later. We use automated discussions on all MRs for things like "Did you update the README?".
I couldn't make the tests pass on my system since we're on go 1.14 and `testing.T.TempDir` isn't available, but it looks like CI is present so I'm hoping to watch it pass there.
=> Adds creation of Merge Request discussions

README.md, cmd/issue_show.go, cmd/mr_show.go, cmd/util.go, go.mod, internal/config/config.go, internal/config/config_test.go, main.go
The lab config heirarchy is:
1. ENV variables (LAB_CORE_TOKEN, LAB_CORE_HOST)
- if specified, core.token and core.host values in
config files are not updated.
2. "dot" . user specified config
- if specified, lower order config files will not override
the user specified config
3.  .config/lab/lab.toml (global config)
4.  .git/lab/lab/toml (worktree config)
Values from the worktree config will override any global config settings.
=> Config rework

cmd/issue_create.go, cmd/issue_edit.go, cmd/issue_note.go, cmd/mr_create.go, cmd/mr_note.go, cmd/mr_note_test.go, cmd/snippet_create.go, cmd/snippet_create_test.go
Solves issue #376 wrt string handling in `--message | -m` flags.
=> flags: fix "message" string handling

cmd/mr_checkout.go
This merge request is pretty simple, only adds the '<id>' text to the `lab mr checkout -h` command.
No issue opened for that.
=> mr_checkout: fix usage message

cmd/issue_show_test.go, cmd/root.go, cmd/root_test.go, internal/git/git.go, internal/git/git_test.go
Mostly related to issue #438, this patchset fix the discovery of the remote the user forked from and also adds a fallthrough path in case none of the default options are met.
A test code was added to the new internal/git/git.go:GetLocalRemotesFromFile() function: although not entirely necessary we need to make sure the `git config --get-regex` behavior doesn't change over time.
=> add fallthrough path for forkedFromRemote

internal/config/config.go
When running 'lab' for the first time users see the message
Create a token here: profile/personal_access_tokens
This does not indicate the scope of the token and the URL is incorrect.
Fix the URL and output a better token creation message.
Reported-by: David Arcari <darcari@redhat.com>
=> config: Provide better PAT information message

internal/git/git.go, internal/git/git_test.go, testdata/test.git/config
Solves issue #456 by checking `remote.<name>.pushurl` before `remote.<name>.url`.
=> git: consider pushurl gitconfig option

cmd/root_test.go
Test_config_gitConfig_* tests were failing while I was trying to run `go test` locally.
The reason was that these tests are looking for `/home/travis/...` path, which, obviously doesn't exist.
However, at the same time, I also understand why the tests don't use a "generic" home dir: it would erase/modify my local lab config.
Because of that, I thought that instead of failing, the tests could only be skipped in case the path is invalid.
=> root: skip test instead of fail if running locally

cmd/issue_edit.go, cmd/issue_edit_test.go, cmd/issue_note.go, cmd/mr_edit.go, internal/gitlab/gitlab.go
Add the ability to edit Merge Request descriptions and comments.  As a bonus, this also allows the editing of Issue comments.
=> Merge Request edit functionality

cmd/issue_show.go, cmd/mr_list_test.go, cmd/mr_show.go, cmd/mr_show_test.go, internal/git/git.go
The GitLab UI provides the ability to show comments that were made on
patches, and this functionality is missing from lab.
Enhance 'lab mr show' to display the diffs and add a --color-diff option
to show the diffs in color (red for removals, green for additions).
Note that due to the design of the GitLab API, not all diffs are viewable.
example of output:
```
-----------------------------------
#419174696: prarit started a discussion at 2020-09-26 19:07:34.121 +0000 UTC
this is a comment
-----------------------------------
#419174735: prarit commented at 2020-09-26 19:07:34.074 +0000 UTC
This is a reply to the comment.
-----------------------------------
#419174767: prarit commented at 2020-09-26 19:07:52.391 +0000 UTC
This is another comment.  No replies. …
```
=> Add commit discussion functionality

cmd/issue_note.go
The logic on the flag is reversed, and should be false instead of true.
=> mr note: Fix reply update flag.

cmd/mr_list.go, internal/config/config.go
The user authentication can fail if the token or load_token field is
incorrect.  lab fails with, for example,
2020/10/13 13:29:46 config.go:194: GET https://gitlab.com/api/v4/user: 401 {message: 401 Unauthorized}
which is not human-readable.
Output a better and human friendly authentication error message.
=> config: Add a better user authentication error message

cmd/mr_create.go, cmd/mr_test.go, testdata/test.git/config
Solves issue #466 by adding `remote.pushDefault` and `branch.<name>.pushRemote` as possible source remote options.
Also, the patch also adds a test case for the function.
=> mr_create: add git-config options as possible source remotes

cmd/ci_status_test.go, cmd/ci_trace_test.go
The Travis CI results are now reversed and are causing ci_status_test
to fail when checking the expected output.
Reverse the excepted output.
=> ci_status_test: Reverse expected output

cmd/mr_create.go, cmd/mr_create_test.go, internal/git/git.go
The 'lab mr create' command provides changelog output as part of the
default commit message in which each commit, author, and age of commit
is displayed.  The output does not contain a diffstat and some
users find diffstat useful for both commit verification and for code
review.
Remove the age of the commits from the output and provide the diffstat
output in the create output.  Like the rest of the changelog, the new
diffstat output is commented so it is not included in the merge request
description by default.
=> mr create: Update 'mr create' output and add --cover-letter option

cmd/mr_checkout.go, cmd/mr_checkout_test.go
When an existing branch is checked out, the following error is output:
fatal: Refusing to fetch into current branch refs/heads/NeOSEQFT of non-bare repository
2020/10/02 10:49:51 mr_checkout.go:76: exit status 128
Output a better error when a merge request branch already exists.
Suggested-by: Sandro Jaeckel <sandro.jaeckel@posteo.de>
=> mr_checkout: Provide better error when branch already exists

cmd/ci_run.go, cmd/ci_status.go, cmd/fork.go, cmd/issue.go, cmd/issue_create.go, cmd/issue_edit.go, cmd/issue_list.go, cmd/issue_note.go, cmd/issue_show.go, cmd/mr.go, cmd/mr_create.go, cmd/mr_discussion.go, cmd/mr_edit.go, cmd/mr_list.go, cmd/mr_note.go, cmd/mr_show.go, cmd/project_create.go, cmd/project_list.go, cmd/snippet_create.go, cmd/snippet_list.go
Fix up some typos and capitalization issues in the help output.
There is no functional change in this commit.
=> lab: Fix --help output

cmd/mr_list_test.go
The Test_mrListByTargetBranch is failing with
--- FAIL: Test_mrListByTargetBranch (0.97s)
mr_list_test.go:138:
Error Trace:	mr_list_test.go:138
Error:      	Not equal:
expected: "#1 Test MR for lab list"
actual  : "#6 test award emoji"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-#1 Test MR for lab list
+#6 test award emoji
Test:       	Test_mrListByTargetBranch
because test MR #6 was modified and now has an 'updated_at' date newer
than #1.
Change the Test_mrListByTargetBranch test so that it correctly detects #1
again.
=> mr_list_test: Fix Test_mrListByTargetBranch

cmd/issue_note.go, cmd/mr_approve.go, cmd/mr_browse.go, cmd/mr_close.go, cmd/mr_discussion.go, cmd/mr_edit.go, cmd/mr_merge.go, cmd/mr_rebase.go, cmd/mr_show.go, cmd/mr_thumb.go, cmd/root.go, cmd/util.go, cmd/util_test.go
Add MR contextual support for issue 204.  This allows users to checkout a branch and execute commands on that branch without specifying the MR ID.  For example,
```
git checkout <branch_for_MR_100>
lab mr show
#shows MR for 100
```
=> Add MR contextual command support for issue 204

cmd/mr_discussion.go
lab commit fd4bc293d29c ("Add mr discussion creation") added a 'comment'
alias for the discussion command.  This alias was already in use by
the note command and should not be used.
Drop the 'comment' alias from the 'mr discussion; command.
=> discussion: Drop 'comment' alias

cmd/mr_note.go
Executing
lab mr checkout <mr_id>
lab mr comment
results in the incorrect error
"Error: requires at least 1 arg(s), only received 0"
Remove the requirement for a single argument to be provided by the
'mr note' command.
=> mr_note: Fix error with contextual command

cmd/mr_unapprove.go, internal/gitlab/gitlab.go
lab has functionality to approve an MR, but not remove the approval if the
reviewer has changed their mind.
Add 'mr unapprove'.
=> lab: Add 'mr unapprove' command

README.md
This PR updates readme in response to the recent introduction of the `lab` formula to default Homebrew formulae. 🎉 
Checks one of the items listed in https://github.com/zaquestion/lab/issues/406#issue-686955945
> This issue aims to capture the immediate todos to get `lab` fully re-homed functionally speaking. (no particular order)
> 
> * [ ]  Replace Travis CI with GitLab CI
>   * [ ]  Update `.goreleaser` to upload artifacts as GitLab release artifacts
>   * [x]  **Update homebrew tap home? Submit formula to homebrew core?**
=> Use official `lab` Homebrew formula

internal/git/edit.go
Golang exec.Command() considers empty args as valid/normal arguments to be
passed to the program to operate against.  In the case of a text editor an
empty filepath may causes different actions depending on the one the user
uses, for example: (1) a "new buffer" (nano) or (2) the current path (vim)
are opened for edit.
With that, when the user call "lab mr create" without specifying a file (-F)
the text editor open two files for edit: the "empty file" (triggering an
undefined behavior) and the actual ISSUE_NOTE/MR_NOTE/MERGEREQ.  This patch
adds a conditional to ignore the args passed to the text editor in case it's
empty, avoiding such behavior.
=> edit: ignore empty argument

cmd/issue_note.go
lab commit bd1c969eed38 ("mr: Migrate commands to use MR mapping code")
introduced MR context commands to lab, removing the need to enter in an
Merge Request ID if the command was being executed on a tracked branch.
After this code was introduced it is easy for a user to inadvertently
write to the wrong MR using, for example, 'lab mr note'.
It is simple to provide additional context in the editor, for example,
"This comment is being applied to OPEN Merge Request 52"
to avoid any confusion.
Update the default note editor message to output the status and MR number
being commented on.
=> mr note: Provide more information in comment message

cmd/root.go, cmd/root_test.go, cmd/version.go, cmd/version_test.go
Change some pieces of "help" documenation:
* `lab --help` and `lab help` don't prompts `git-help` output anymore.
* `lab version` doesn't sigfaults anymore: solved by removing the "PreRun" callback.
Solves issue #480 .
=> couple changes to help cmd to improve user experience

cmd/issue_note.go
lab commit f64a2421023a ("mr note: Provide more information in comment message")
added additional context about Merge Requests in the editor.  The same can
be done for Issues, for example,
"This comment is being applied to CLOSED Issue 3."
Update the default note editor message to output the status and Issue number
being commented on.
=> issue note: Provide more information in comment message

internal/config/config.go
It seems to be a good idea to first check the mandatory config opts before leaving/returning from `LoadMainConfig`, avoiding strange error messages as `lab` tries to perform actions with empty opts.
=> config: check mandatory config opts before moving on

internal/git/edit.go
Currently all the saved data in the EDITMSG file is lost when something
goes wrong during editing of an Issue or MR.
Only delete the file if the editor succeeds, and output an error message
with the location of the saved data.
Closes #332 
=> edit: Backup EDITMSG in case of failure

internal/config/config.go
Instead of setting the 'home' var early, only set it in case XDG_CONFIG_HOME
isn't set. 'home' var is only useful for composing the config path, nothing
else.
=> config: home dir is only useful if XDG_CONFIG_HOME isn't set

cmd/issue_move.go, cmd/util.go, internal/gitlab/gitlab.go
In large projects with groups, and extended namespaces, issues
occasionally get filed in the wrong project.  GitLab's API provides
functionality to move an issue from one project to another.
Add 'lab issue move <new_project>'.
=> lab: Move issues from one project to another

cmd/mr_discussion.go
Add 'block' and 'thread' aliass for the 'mr discussion' command.
=> mr discussion: Add aliases

cmd/mr_approve.go, cmd/mr_test.go, cmd/mr_unapprove.go
lab: Add --with-comment option to mr approve and unapprove commands
Some users would like to add a comment when they approve or unapprove a
merge request.
Add a --with-comment option to the 'mr approve' and 'mr unapprove'
commands.
=> Approve and Unapprove with comment

cmd/mr_list_test.go
A new MR, #18 MR for approvals and unapprovals, was pushed to the lab
testing tree to test approval and unapproval functionality.
Test_mrListByTargetBranch must be updated to point at MR #18.
=> mr list test: Update Test_mrListByTargetBranch

cmd/mr_approve_test.go, cmd/mr_show.go, cmd/mr_show_test.go, cmd/mr_test.go, cmd/mr_unapprove.go, internal/gitlab/gitlab.go
Display the list of reviewers in the 'lab mr show' command, and add tests for 'lab approve' and 'lab unapprove'.
=> MR approvals: Add show functionality and tests for commands

cmd/clone.go, cmd/fork.go, cmd/mr_checkout.go, cmd/mr_show.go, cmd/project_create.go, cmd/util.go, cmd/util_test.go, internal/gitlab/gitlab.go
This MR bring the patch created by @eedgar in MR #477, which turns HTTP protocol as the default for forking a repo.
However, it turns SSH off and let other places that relies on the protocol format without changes.
The additional patch(es) make HTTP possible through a command flag (`--http`), letting SSH still as the default.
But now, the user can `lab fork --http`, `lab clone --http`, and others, to use the HTTP URL scheme instead of the SSH.
Quick note for reviewers: the GitLab API token for HTTP need to have both `{read,write}_repository` capabilities set since they're the ones allowing GIT-over-HTTP trafic.
=> Enable HTTP protocol for different commands

cmd/issue_note.go, cmd/issue_show.go
The information in the system notes is important.  For example, changing
a merge request description will generate a system note.  Engineers find
this useful in the WebUI and it is easy to show in 'lab mr show' or
'lab issue show'.
System notes cannot have replies so there is no reason to output the
note ID.  Instead, preface system notes with an asterisk '*'.
This change adds lines like, for example,
* prarit changed the description at 2020-11-12 20:36:39.425 +0000 UTC
to the lab show commands.
=> show: Add system note output

cmd/issue_show.go, go.mod, go.sum
Currently lab dumps html content directly into text comments.  For
example,
Current checkin policy requires:<br>&emsp;
This html should be converted into text for display in show commands.
Convert html comments into text for the lab show commands.
=> lab show: Convert html comments to text

cmd/mr_approve.go, cmd/mr_close.go, cmd/mr_discussion.go, cmd/mr_merge.go, cmd/mr_rebase.go, cmd/mr_unapprove.go
The commands use parseArgsWithGitBranchMR() to parse non-flag arguments,
which will return the MR id associated with the current branch if no
id is specified.
That behavior makes a lot of sense, but can only work if the option parser
doesn't enforce the id to be specified.
=> mr: Don't set minimum number of args

cmd/mr_merge.go, cmd/mr_rebase.go
Those are likely copy+paste errors, in particular merging is pretty
much the opposite of deleting ...
=> mr: Remove questionable aliases

cmd/issue_edit.go, cmd/issue_note.go, cmd/issue_note_test.go, cmd/mr_edit.go, cmd/mr_note.go, cmd/mr_note_test.go, internal/gitlab/gitlab.go
Currently lab does not have functionality to resolve threads.  Add a
--resolve option to the 'mr note' command that will result in the thread
being resolved.  Empty comments are allowed for the --resolve option.
Add a --resolve option to the 'mr note' command.
=> mr note: Add --resolve option

cmd/mr_show.go
The remote name in the output isn't separated from the next word.
=> mr/show: Fix glitch in error message

cmd/mr_list.go, cmd/mr_list_test.go
Add a --sort option to display MRs in either ascending or descending order.  Add a --order option to display MRs in the order they were created, or in the order they were updated.
=> mr list: add --sort and --order options

Makefile
There is no 'deps' target whatsoever. OTOH, 'build' was not being considered
as PHONY. This patch change one for another.
=> Makefile: move PHONY target from 'deps' to 'build'

cmd/ci_status.go, cmd/ci_status_test.go, cmd/ci_trace.go, cmd/ci_view.go, cmd/mr_create.go, cmd/mr_test.go, cmd/util.go, internal/git/git.go, testdata/test.git/config
While the local branch name usually matches the remote one, this is
not necessarily the case, and the automatic detection of a MR or pipeline
fails.
Handle those cases as well by figuring out the remote tracking branch
and use that instead of the local name if possible.
Fixes #360
=> Use the remote tracking branch where appropriate

cmd/issue_show.go, cmd/issue_show_test.go, cmd/mr_show.go, cmd/mr_show_test.go, cmd/util.go
Prevent ANSI control chars from being prompted to stdout and stderr in case lab is piping it and not printing in a usual terminal.
Fixes #519 .
=> show: check output type before rendering Markdown

cmd/ci_status_test.go, cmd/ci_trace_test.go, internal/gitlab/gitlab.go
When we filter the list to only show the latest job of each stage+name
combo, we mess up the expected order of jobs in the pipeline.
Address this by sorting the filtered list before returning it.
Fixes https://github.com/zaquestion/lab/issues/471
=> ci: Sort list of displayed jobs

cmd/issue_note.go
Comment paragraphs specified via -m on the command line take precedent
over quoting the replied comment. However if no -m flag is specified,
the corresponding variable is an empty array, not nil. As a result,
we never reach the code that marks the replied comment as quote.
=> issue_note: Fix quoting of replied comment

cmd/mr_create.go, cmd/mr_edit.go, cmd/mr_list.go, cmd/mr_test.go
Gitlab supports marking a merge request as draft to indicate that it is not ready to be merged. This is supported in the web UI (actions to mark as draft/ready, disabled merge button in draft MRs), but not explicitly exposed in the API: Drafts are simply indicated by prefixing the MR title with "Draft:", "[Draft]" or "(Draft)" (or previously "WIP)[0].
lab therefore kind of supports the feature already, but it still seems reasonable to export the feature explicitly rather than via manipulating the title (although that's of course what the implementation does under the hood).
[0] https://docs.gitlab.com/ee/user/project/merge_requests/work_in_progress_merge_requests.html
=> Add support for draft merge requests

cmd/mr_approve.go, cmd/mr_approve_test.go, cmd/mr_checkout.go, cmd/mr_close.go, cmd/mr_list.go, cmd/mr_list_test.go, cmd/mr_reopen.go, cmd/mr_reopen_test.go, cmd/mr_show.go, cmd/mr_show_test.go, cmd/mr_test.go, cmd/mr_thumb.go, cmd/mr_unapprove.go
In Gitlab's UI, issues appear as #123 and merge requests as !123.
Follow that convention when outputting MR IDs.
=> RFC: Use bang to denote MR IDs

cmd/ci_status.go, cmd/ci_status_test.go, cmd/ci_trace.go, cmd/ci_view.go, internal/gitlab/gitlab.go
Gitlab allows setting up pipelines that are associated with a
merge request rather than a branch/tag ("detached")[0].
Merge request pipelines may be created instead of or in addition
to the regular branch/tag pipeline, and can use a different set
of jobs.
When merge request pipelines are used, they control whether a MR
can be merged, so their status is clearly interesting.
Unfortunately if both branch and MR pipelines are enabled, which
one ends up being the last one associated with a commit is random.
Address this by adding an explicit --merge-request flag to the
various ci subcommands to explicitly refer to the detached pipeline.
[0] https://docs.gitlab.com/ee/ci/merge_request_pipelines/#pipelines-for-merge-requests
=> Add support for merge request pipelines

cmd/mr_test.go
The expected output changed since the test was written. Adjust it
to fix the test.
=> mr: Fix draft test

cmd/mr_show.go
The current code still assumes a minimum of one argument (the MR ID),
but we can determine that automatically nowadays.
=> mr_show: Fix --patch option with no arguments

cmd/ci_view.go, cmd/mr_edit.go, cmd/root_test.go, cmd/util.go
Currently we check whether a flag's current value differs from its
default in order to skip the value from the config file. That works
in most cases, but as a result it is not possible to override a value
from the config by explicitly passing the default value:
[mr_show]
comments = true
$ lab mr show --comments=false
Fix this by checking the flag's Changed property instead.
=> util: Always override config file flags from the command line

cmd/ci_trace.go
When splitting an argument into branch and job name, we assume that
the string only contains a single ':'. It's a legal character in
job names though, so handle that edge case by limiting the number
of substrings.
=> ci: Handle job names with colons in filterJobArg()

cmd/issue_close.go, cmd/issue_reopen.go, cmd/issue_reopen_test.go, cmd/issue_test.go, internal/gitlab/gitlab.go
Right now there's support for reopening merge requests, but not issues.
Plus when closing an issue, it can be useful to mark it as a duplicate of another issue.
=> Support duplicating and reopening issues

cmd/issue_edit.go, cmd/mr_edit.go, cmd/mr_list.go, cmd/project_list.go
By default, flags are sorted alphabetically. However there are some
cases where it makes more sense to group related flags together,
like --label/--unlabel, --assign/--unassign or --draft/--ready.
Disable flag sorting in those cases.
=> Disable flag sorting for some commands

cmd/fork.go, cmd/fork_test.go, internal/gitlab/gitlab.go
Allow the user to specify three fork properties: `name`, `namespace` and `path`.
With it the user can fork the same project to different namespaces with different names, working around possible conflicts.
Fixes #488
=> fork: enable different name, namespace and path on destination

cmd/mr_test.go
It should remove an eventual branch left-over from a previous run,
not a left-over branch from a different test, whoops.
=> test: Fix draft-mr test preparation

cmd/project_create.go, cmd/project_create_test.go, go.mod, go.sum, internal/gitlab/gitlab.go
Depends on https://github.com/xanzy/go-gitlab/pull/950
Manually tested:
```
lab project create lab-cli-testgroup/labproject5 # in group
lab project create lab-cli-testgroup/sub/labproject5 # in sub group
lab project create lab-cli-testgroup/sub/deeper/labproject5 # in nested subgroup
```
Special handling required for each case.
=> Support namespace/groups for project create

cmd/issue_note_test.go, cmd/issue_show.go, cmd/mr_show.go, go.mod
A couple of minor fixes and tweaks, and a bigger one: Render markdown in comments as we do for the desciption.
The last change means that only the header line of new comments is printed in bold, but IMHO this is enough for them to stand out.
And the readability improvement is quite significant:
=> Improve comments appearance

cmd/mr_list.go
Simple fix/change in the mr_list flag description for both `order` and `sort` flags.
=> mr_list: fix order and sort flags description

.gitlab-ci.yml, .goreleaser.yml, docs/build.sh
note: for docs to work on gitlab themselves we will need to get a jeckyll/markdown renderer rigged up, but this much will keep the files up to date
=> (gitlab-ci) add release jobs for goreleaser and docs gen

cmd/issue_create.go, cmd/issue_edit.go, cmd/issue_edit_test.go, cmd/issue_list.go, cmd/label_create.go, cmd/label_delete.go, cmd/label_list.go, cmd/label_test.go, cmd/mr_create.go, cmd/mr_edit.go, cmd/mr_list.go, internal/gitlab/gitlab.go
Currently label names have to be specified by their full name, and
any partial or non-existing names end up creating new labels. Instead,
map the list of names we get on the command line to the real labels.
This allows user-friendly (read: long and descriptive) label names
without losing command line convenience.
=> labels: Support partial label names

cmd/util.go
Force casting for syscall pkg variables to solve Windows and Linux different return types.
Fixes #554 .
=> util: fix syscall.Stdout and Stderr fd values on for Windows

cmd/mr_list_test.go
!22 got merged, so no longer shows up in the list by default.
=> mr_list: Update test (again)

.goreleaser.yml, internal/config/config.go
chenrui333 noted in #558 that the goreleaser test for lab was failing.
The test is a simple execution of the git wrapper capabilities of lab.
The test does:
git init
touch haunted
touch house
git add haunted house
git commit -a -m "Initial Commit"
lab ls-files
and expects the output of the last command to be
haunted
house
The test currently fails on the command line with
```
[prarit@prarit dummy (master)]$ LAB_CORE_HOST=foo LAB_CORE_USER=bar LAB_CORE_TOKEN=baz lab  ls-files
Create a token with scope 'api' here: profile/personal_access_tokens
Enter default GitLab token, or leave blank to provide a command to load the token:
```
instead of displaying the list of files.  This occurs because the code
does not check to see if LAB_CORE_TOKEN is set before querying the user
for a token.
Check …
=> lab: Check that LAB_CORE_TOKEN is set before querying user for a token

cmd/issue_create.go, cmd/issue_edit.go, cmd/issue_list.go, cmd/issue_list_test.go, cmd/milestone.go, cmd/milestone_create.go, cmd/milestone_delete.go, cmd/milestone_list.go, cmd/milestone_list_test.go, cmd/milestone_test.go, cmd/mr_create.go, cmd/mr_edit.go, cmd/mr_list.go, cmd/mr_test.go, internal/gitlab/gitlab.go
Milestones are useful to associate issues/MRs with some target (usually a release).
This adds some basic support, following the existing handling of labels.
=> Add support for milestones

cmd/ci_artifacts.go, cmd/ci_artifacts_test.go, internal/gitlab/gitlab.go
Quoting the commit message:
Pipeline jobs can produce files that are uploaded to gitlab and made
available for download.
Support this with a new `ci artifacts` subcommand, which either
downloads the entire artifacts archive, or a singe file from
that archive when the --artifact-path option is used.
I originally implemented the single-artifact case as positional argument
as discussed in #232, i.e. "remote branch:job path", but then decided
against it:
- I like how `lab` generally does the right thing when a positional
argument is omitted, but that's tricky when there are four of them;
in particular job name and path are problematic, as those are just
arbitrary strings as far as we know
- command line flags can be set up in the config file (for example
if the pipeline only produces a single …
=> ci_artifacts: Allow downloading artifact(s)

cmd/mr_show.go
I noticed that 'lab mr show' shows Merge Requests that need a rebase as
status "open" with no further information.
The MergeRequest struct has a MergeStatus field that returns
"can_be_merged" or "cannot_be_merged".  The "cannot_be_merged" state can
be used to return better status information to the user.
Add an "open (needs rebase)" status.
=> mr_show: Add MR status "open (needs rebase)"

cmd/mr_list_test.go
The test for milestone support creates and closes a MR on origin,
with the result that the test case for closed MRs ended up being
pushed off the list, given that only a limited number is shown
by default.
List all closed MRs to make it appear in the listing again.
=> mr_list: Fix test

cmd/root.go, main.go
The help describes -h as a valid option:
Flags:
-h, --help      help for lab
But using it fails with:
$ lab -h
unknown option: -h
Fix this.
=> Fix the -h lab option

cmd/mr_list_test.go
mrListStateClosed test is failing with not finding the output "!5 closed
mr".  This occurs because the output contains only the first 20 closed
MRs.  If all the closed MRs were listed the test will pass.
Modify the mrListStateClosed test to list all closed MRs.
=> mr_list_test: mrListStateClosed fix

cmd/fork.go
The fork command can be used in two ways:
1. when passed a namespaced project name (e.g. "SomeGroup/AwesomeProject"),
the project is forked (and optionally cloned)
2. without arguments, the project name is determined from the "origin"
remote in the current repository, forked and added as remote
The second mode currently doesn't work if the repository pointed to by
"origin" doesn't use the Namespace/Project structure gitlab expects.
Support that use case by also picking the second mode when the passed
argument corresponds to an existing remote.
Fixes #563
=> fork: Allow forking from remotes other than "origin"

cmd/issue_list.go, cmd/mr_list.go, cmd/mr_list_test.go
Search is as useful for merge requests as for issues, so support
the same option as `lab issue list`.
=> mr_list: Support search

cmd/mr_create.go
Hi,
This fixes an issue where the target remote name can be wrong, if the repository wasn't forked from the target at first.
Thanks!
=> mr_create: fix the target remote

internal/git/git.go
Hi,
This PR fixes one error message in internal/git and the UpstreamBranch function which has a too strict expectation on the local remote names.
Thanks!
=> Internal git fixes

cmd/issue_create.go, cmd/issue_move.go, cmd/mr_checkout.go, cmd/mr_create.go, cmd/root.go, cmd/root_test.go, cmd/snippet_create.go, cmd/util.go, internal/config/config.go
The goal of this PR is to allow the user to configure what should be the default remote. The current logic tries to guess what should be the default remote by looking at the "origin" and "upstream" remotes if defined, and at branches such as "main" and "master". But having those remotes and branches is not always the case, and even so they could hold a wrong value (for lab).
This PR adds the ability to explicitly configure the default remote, using a new `core.default_remote` parameter in the configuration. While it is probably not a good idea to define this globally, the configuration file can also be in the repositories `.git` directories, as well as in the `.git/worktrees/` directories when using Git worktrees. In such cases, having the ability to explicitly set the default remote is …
=> Allow configuring a default remote

cmd/ci_status.go, cmd/ci_trace.go, cmd/issue_list.go, cmd/issue_show.go, cmd/label_list.go, cmd/mr_list.go, cmd/mr_show.go, cmd/project_list.go, cmd/root.go, cmd/snippet_list.go, cmd/util.go, internal/git/git.go
Replicate git's behavior of piping output through a pager when it
doesn't fit a single screen. This is not only more convenient than
piping into less on the command line, but preserves terminal features
like colored output as well.
I do have a local follow-up to add a global --no-pager option like git
as well, if that's wanted (not sure that's the case, so leaving it out
right now)
=> cmd: Pipe output through pager in terminals

cmd/ci.go, cmd/ci_artifacts.go, cmd/ci_status.go, cmd/ci_trace.go, cmd/ci_view.go, cmd/util.go, go.mod, go.sum, internal/gitlab/gitlab.go
This MR enables `lab` to follow pipelines that are kept in other projects other than the current, where the source code is,
this is called [multi-projects pipeline](https://docs.gitlab.com/ee/ci/multi_project_pipelines.html).
For that, a new persistent flag was added to all `lab ci` commands:
```
--follow   Follow downstream pipelines in a multi-projects setup
```
e.g.
```
$ lab ci artifacts upstream --follow --merge-request
```
One of the issues here is that we don't have a test infrastructure to properly test it.
I've tested within the company's infrastructure that I work and seems to be fully working.
I'm afraid the only thing we can do is to wait for people to use it.
=> add multi-project CI pipeline support

cmd/label_list.go, cmd/mr_list.go
This patchset removes a config error message during `mr_list` and make the label ambiguity just fine, instead of returning an error.
Fixes #580
=> Fix label exact match

cmd/mr_create.go
Both options can fail, for example when the referenced label/milestone
doesn't exist. It is better to fail early in that case, and not wait
until the user composed a MR description in the editor (when none was
passed on the command line).
=> mr_create: Evaluate label/milstone flags before description

main.go
We skip init when the first argument is help (`lab help mr`), do the
same for the last argument as well (`lab mr create --help`).
This allows printing out subcommand help from a git tree without
a corresponding gitlab token.
=> main: Also skip init for subcommand help

cmd/mr_create.go, cmd/util.go
Fix panic during a `lab mr create -c --draft` with an empty cover-letter.
Fixes #587
=> mr_create: check for empty msg before acting

cmd/issue_list.go, cmd/mr_list.go
Add `all` to the `lab mr list --help` command under `-s, --state string` paramenter.
With that the user don't need to guess this option is available.
=> mr_list: fix help message wrt MR state

cmd/mr_create.go, cmd/mr_create_test.go, internal/git/git.go, internal/git/git_test.go
First time GitLab users can make mistakes that result in a large merge
request being generated.  For example, new users may get the target branch
wrong, or push a branch that hasn't been updated, etc.  These errors always
result in way more commits than intended being pushed.
After a push to one of their hosted repositories, GitLab provides a URL
to a webpage that allows users to change the target branch and look at the
commits that are going to be pushed.  One convenient value on that page is
the number of commits that are being pushed.  In order to prevent users
from making simple mistakes, like the above, it would be good to also
provide that information the default 'lab mr create' message.
Provide the number of commits in 'lab mr create'.
Signed-off-by: Prarit Bhargava …
=> mr_create: Add number of commits to create metadata

cmd/mr_discussion_test.go, cmd/mr_note_test.go
not sustainable and these test should be dealt with as they will pass
for the most part if any one of them does as they only verify the
presence of a note / discussions
Perhaps they should just be removed?
=> fix: (mr_note) move tests to new dumping ground

cmd/util.go, cmd/util_unix.go, cmd/util_windows.go
Add OS-specific files for handling syscalls.
This file should be used as a compatibility layer.
Fixes #598
NOTE: this MR is required to allow our next release.
=> util: create os-specific layer for syscalls

cmd/util_darwin.go, cmd/util_unix.go
And we have yet another OS-specific issue to solve.
This time is a diff between Linux and Darwin (MacOS):
* Linux ARM64 lacks DUP2() syscall, so we need to use DUP3(), however...
* Darwin lacks DUP3(), so we need to create a specific file for it.
Down side of that is: great part of _unix.go file must be replicated in _darwin.go one.
For the sake of getting a new release out of the door, I'm literally copying+pasting the code, but it should (I HOPE) have a better way to handle this "partial" incompatibility.
EDIT: dup3() is available from userspace in Linux ARM64 glibc, but we don't have access to it from Go lib and we can't rely every system uses glibc.
=> util: fix dup2() usage for Linux and Darwin

cmd/issue_show.go, cmd/issue_show_test.go, cmd/issue_subscribe.go, cmd/issue_subscribe_test.go, cmd/issue_unsubscribe.go, cmd/mr_show.go, cmd/mr_show_test.go, cmd/mr_subscribe.go, cmd/mr_subscribe_test.go, cmd/mr_unsubscribe.go, internal/gitlab/gitlab.go
For projects where one is only tangentially involved, it sometimes
makes sense to subscribe to an individual issue or merge request
rather than the project as a whole.
Support that with corresponding subcommands.
=> Add subscribe/unsubscribe subcommands

cmd/fork.go, cmd/fork_test.go
Today, `lab` only allows the user to setup the <user> or "upstream" remotes in a fork or clone process. This patch enables the option `--remote-name` (or `-r`) for setting a custom remote name. Somewhat the same behavior as `git clone -o`.
=> allow user to set custom remote name on fork

internal/git/git.go, internal/git/git_test.go, testdata/test.git/config
Some developers like to have the <pushurl> set to nothing (empty) to avoid pushing by mistake to that remote. This patch adds a check for an empty string against <pushurl> and use <url> instead.
=> use <url> in case of an empty <pushurl>

cmd/mr_create.go
Fails out when using -F/-m/-c together in mr_create.
Partially fixes #609.
=> mr_create: error out when using -F, -m and/or -c together

cmd/completion.go
small blunder as `Snippet()` now returns an error and thus `<nil>` was written to stdout after the script
=> fix `<nil>` output in completion script generation

cmd/issue_list.go, cmd/mr_list.go
The "all" state was not being added to the completion code. This patch adds it alongside the other options.
=> add "all" state to completion action values for MR and Issues

cmd/issue_list.go, cmd/mr_list.go, cmd/project_list.go, cmd/snippet_list.go, cmd/util.go
A user noticed an issue in which 'lab mr --list' and 'lab mr list'
returned lists of 10 and 20 entries respectively.  Both effectively call
the same code in the mr_list file and the only difference is that
LabPersistentPreRun() is run on 'lab mr' and 'lab mr list' respectively.
It appears that IntVarP is not handled properly by viper (there are a few
reports of other issues with IntVarP online) and the suggestion is to
use StringVarP in place of IntVarP.
The IntVarP value is used as the number of entries returned per page
for the list commands of MRs, Issues, Projects, and Snippets.  In all of
these cases the user modified value was not being honoured in the
code so fixes for these are also included.
=> lab: Clean up IntVarP usage

cmd/label_list.go, cmd/mr_edit.go, cmd/util.go, cmd/util_test.go, internal/gitlab/gitlab.go
Add the `--target-branch` (or `-t`) flag to the mr_edit command, allowing the user to update the target branch for that specific MR through `lab`.
=> allow user to update target branch while editing an MR

install.sh
Make installer script POSIX compliant by removing bashisms and make it compatible with sh
Resolves #339
=> Make installer script POSIX compliant

README.md, cmd/fork.go, cmd/root.go, internal/git/git.go
We have partially supported the `hub` tool for a while, but considering it's now deprecated we should just remove any mention of it as "part of" `lab`, or `lab` wrapping it.
=> Completely drop hub support

cmd/mr_show.go, docs/lab_mr_show.md
The help for '--no-color-diff' is exactly wrong.
Fix --no-color-diff so that it outputs the correct message.
Reported by: Lenny Szubowicz <lszubowi@redhat.com>
=> mr show: Fix --no-color-diff help

cmd/edit_common.go, cmd/mr_create.go, cmd/mr_edit.go
Add `-F` option to mr_edit, allowing the user to pass a file as input for resetting the MR description.
=> mr_edit: allow user to reset MR description from file

cmd/root.go, cmd/root_test.go
A few users have been asking about lab's purpose relative to git.  The current description of the tool "A Git Wrapper for GitLab" is not accurate and should be updated to reflect that lab is a command line utility for GitLab.  
Also, output a warning for git wrapper users -- we know this code is going away in the future and we should be encouraging people to not write scripts that depend on lab's git wrapper.
=> Git command warning

cmd/mr_show.go, cmd/mr_show_test.go, internal/gitlab/gitlab.go
Several users have requested that the list of approvers and reviewers be
added to the output of the 'lab mr show' command.  This list is useful for
authors to know who to request reviews from, and to see the eligible list
of approvers.
Add Approvers, Approval Groups, and Reviewers to the output of 'lab mr
show'.
=> mr show: Display output for approvers and reviewers

cmd/mr_checkout.go, cmd/mr_checkout_test.go
Users have reported a minor annoyance with 'lab mr checkout':
lab mr checkout 3
lab mr checkout 3
and is returned a "ERROR: mr 3 branch branchname already
exists."
In most cases that I can think of the person checking out the MR
wants the latest version of the the code in the MR, not old code.  It
would be convenient to have a --force option that would delete and
overwrite the existing MR branch.
Add 'lab mr checkout --force' option that overwrites an existing MR branch
checkout.
=> mr checkout: Add --force option

cmd/issue_show.go, cmd/mr_show.go, cmd/show_common.go
This PR fixes two issues: 
1. the line wrapping behavior that `glamour` lib has enabled by default at the mark of 80 columns, which I think shouldn't, since the user is expecting to see what was exactly sent;
2. use only 16 ANSI colors pallet to allow more simple terminals and pagers to work properly.
If item 2 isn't desirable, I'm fine with dropping it.
Fixes #632.
=> mr_show: fix line wrapping

cmd/mr_create.go, cmd/mr_create_test.go, internal/git/git.go, internal/git/git_test.go
'lab mr create' can incorrectly report the number of commits in a merge reuqest.  This is because the code incorrectly looks at the local source branch rather than the remote source branch when checking the number of commits.  Additionally, the 'lab mr create' also does not error if there are zero commits found between the remote source and remote target branches. 
Fix the number of commits reported by examining the remote source branch and return an error if the number of commits is zero.  
=> mr_create: Check for zero commits in a Merge Request

cmd/root.go
When a user fork a project from nothing the "forkToUpstream" approach is
used, where two remotes are set in the resulting git directory: "origin" and
"upstream", with obvious meanings. However, when the user fork a project
directly from a git directory, where the "origin" remote is already set,
then a new remote with user's username is set for the fork.
The current code for defaultRemote has "origin" as the dominant remote,
however, this remote has two different meanings depending on how the fork
was created: in the first approach, mentioned earlier, "origin" points to
the fork, while in the second it points to the actual upstream project. With
that, users get quite confused why `lab mr list` sometimes lists the MR
against upstream project and other times it lists MRs from the fork.
From …
=> root: make "upstream" the defaultRemote preference

internal/git/edit.go
The editor can also be set with the output of 'git config --get
core.editor'.  Use that if $GIT_EDITOR is not set.
Add core.editor as an additional option to pick the default editor.
Closes #609 
=> edit.go: Add core.editor for default editor

cmd/mr_create.go, cmd/mr_test.go
The GitLab WebUI provides the option to set the source repository and
branch during the creation of a merge request.  This functionality is not
present in lab.
Add a --source option that takes a remote:branch as an argument.  This
option allows users to specify the source remote and branches.
=> mr create: Add --source option

cmd/mr_close.go, cmd/mr_delete.go, internal/gitlab/gitlab.go
This PR adds the ability to delete an MR and also change any occurrence of mr "delete" to mr "close", since `lab mr delete` was being used as an alias to `lab mr close`, which is really misleading considering these are two different actions to GitLab API.
=> mr: add delete command

cmd/todo.go, cmd/todo_list.go, internal/gitlab/gitlab.go
Introduce the bare bones for the TODOs command
with a simple way to list the todo target URLs
so others can incrementally build upon demand.
Signed-off-by: Rafael Aquini <aquini@redhat.com>
=> lab: introduce todo command

cmd/mr_edit.go
The mr edit option --reviewers, incorrectly fails with "aborting: no
changes" because the change to the reviewers is not verified.
Add verification of the reviewers change to the "no changes" check.
=> mr edit: Fix reviewers check

cmd/issue_list.go, cmd/mr_list.go, internal/gitlab/gitlab.go
There were two functions to get the userID from API, UserIDFromUsername and
UserIDByUserName, both were doing basically the same operation. For
simplicity, I removed the second one so now we have UserIDFromUsername and
UserIDFromEmail.
=> gitlab: remove duplicate function for getting used ID

cmd/mr_create.go, cmd/mr_test.go
`errors.Wrapf()` was being used within `log.Fatal()` calls, but it's not the
correct way of doing it. The first adds a message to the error and return
_another_ error if something goes wrong, but if the messages is added
correctly, it returns <nil>. So, whenever this errors were printed, `<nil>`
was being prompted to the user.
=> mr_create: fix output messages

cmd/merge_request.go
The `lab merge-request` command was being used as a shorthand for `lab mr
create`, which, IMO, doesn't make much sense today. And since we already
deprecated most of the shorthand flags for other subcommands, this one seems
a good candidate for deprecation.
=> merge_request: deprecate command

cmd/mr_list.go
Add an option, similar to the --author and --assignee search options, that
allows users to search on the GitLab Reviewer field.
Add a --reviewer option to return the list of all merge requests for
which the specified user is listed as a GitLab Reviewer.
=> mr_list: Add --reviewer option

cmd/mr_list_test.go
A new proposed test has been added that adds an MR to lab-testing.  Change
the latestCreatedTestMR to point to the new MR.
Change the latest created MR value in the 'lab mr list' tests.
=> mr_list_test: Change latest created MR value

cmd/mr_merge.go, internal/gitlab/gitlab.go
Today, the `lab mr merge` command set, by default, the option of merging
only when pipeline succeeds, however, in some workflows (e.g. mine) it's not
entirely true: it's sometimes desirable a merge happens regardless the
pipeline results, for many different reasons.
This patch adds the `lab mr merge --pipeline-succeeds` (or `-p`) for
enabling it, while the default now is to merge directly.
Fixes #653
=> mr_merge: add option for merging immediately

cmd/mr_show.go
The 'mr show' Reviewers lists the first and last names of reviewers and
not usernames.  The other fields (Author, Approved By, etc.) show the
usernames.
Change the 'mr show' command's Reviewers field to show usernames.
=> mr show: Change 'Reviewers' to output usernames

cmd/label_list.go
Check if any label is being really requested before fetching project's
information. This patch improves `list` and `edit` queries by a lot, depending
on the number of labels present in the project.
=> labels: don't fetch labels in case of empty request

cmd/issue_list.go, cmd/mr_list.go
'issue list' sorts issues in descending order and doesn't provide
an option to list them in ascending order that they wree updated.
Add a --sort option to display the issuess by descending (desc) or
ascending (asc) order. Add a --order option display the issues they were
created in or updated at.
=> issue list: Add --sort and --order list options

cmd/issue_list.go, cmd/mr_list.go
The "--assignee", "--reviewer", and "--author" options are not working
because the scope of the variables was incorrect.
Fix thhe "--assignee", "--reviewer", and "--author" list command options.
=> list: Fix list user options

cmd/todo_list.go, internal/gitlab/gitlab.go
The 'todo list' output currently only shows the Todo ID, and a link to the
Todo item.  The WebUI outputs additional information such as the state of
the Merge Requests and Issues, how the Todo entry was added to the Todo
list, etc.
Add an option, --pretty, to output the additional information.
=> todo: Add --pretty output

cmd/mr_merge.go
Other commands, like 'mr reopen' output a nice completion message.  The
'mr merge' command only returns positive status.
Add a successful completion message to 'mr merge'.
=> mr merge: Add successful completion message.

internal/gitlab/gitlab.go
Instead of requesting multiple pages with the default number of items (20),
or requesting more than the max allowed by the API, request as much as
possible items per page, avoiding multiple calls in "list" subcommands.
=> gitlab: fix the number of items per page

cmd/todo_list.go
While looking at some other code I discovered that type Todo contains
a type TodoTarget which contains the information that I was pulling
from the MR and Issue lookups.  These lookups can be dropped and the
code is simplified, there are fewer API calls, and 'lab todo list
--pretty' is faster.
Remove the MR and Issue lookups with the --pretty option.
=> todo list: Remove MR and Issue lookups

cmd/util_bsd.go, cmd/util_linux.go, cmd/util_windows.go
This merge request fixes #680 by re-organizing the cmd/util_* files for specific GOOS.
Darwin and *BSD (mostly FreeBSD) share some ground when it comes to kernel API, with that, a good starting point is to add both families in the same file, suffixed by _bsd.
I know it doesn't hold true for every syscall, but for what we need in `lab` it's good enough.
=> Fix build for BSD OSes family

cmd/todo_list.go
Similar to the 'mr list --all' option, implement a 'todo list --all' to
show all items on the todo list.
=> todo list: Implement --all

cmd/mr_note_test.go
This patch choose another MR to be used as text dump for testing, since
the last one filled up.
=> mr_note_test: change MR ID used for testing discussion

cmd/edit_common.go, cmd/issue_edit.go, cmd/mr_edit.go
Since the label/unlabel code was written the go-gitlab module was
updated and received got the ability to add and remove labels explicitly
instead of the specifying all labels through a single struct member.
With that, we can use these new members in the UpdateLabel struct to
get the job done and solve the issue where it's not possible to unlabel
an issue or MR with a single label, since the array would be ignore for
being "empty".
Fixes #684
=> edit: fix labels update for issue and MR

cmd/mr_show.go
Users have been setting "comments = true" for the mr show command.  This
causes weird output with the --patch output in which the git log is output,
then the comments from the MR is output.
Make a note that --patch and --comments do not work together and stop
the output after the git log is output.
=> mr show: Fix --patch and --comments option output

cmd/mr_create.go, cmd/mr_edit.go
GitLab is planning to fully remove the WIP word from their Draft status [1]
in their 14.0 version, which is about to be released. With that, we should
also error out when the user uses it for their merge requests prefixes.
```
Adding WIP: to the start of the merge request’s title still marks a merge
request as a draft.  This feature is scheduled for removal in GitLab 14.0.
Use Draft: instead.
```
[1] https://gitlab.com/gitlab-org/gitlab/-/issues/228685
[2] https://docs.gitlab.com/ee/user/project/merge_requests/drafts.html
=> Remove WIP terminology support

cmd/mr_show.go
Remove the else clause considering the if ends with return.
=> cmd/mr_show: golint: if block ends with a return statement

cmd/mr_create.go, cmd/mr_create_test.go, internal/git/git.go, internal/git/git_test.go
When the user creates an MR he's prompted with some basic information about what's going to be the MR content:
* commit list
* number of commits
* commit diff statistics
All these information were being created using a "union" approach of `git`: when the information being considered is the union of two different sets (branches) instead of the difference from one set to another (i.e. what's different from branch `<source>` to `<target>`).
The consequence of the union approach appears when the user wants to create an MR using a source branch that is behind of the target branch wrt commits: if the target is 4 commits ahead of the source branch, and the user doesn't rebase before opening the MR, the commits information (all three of them) will present the source branch's commits + 4 from …
=> Fix commit log and diffstat when creating MR

cmd/ci_run.go, cmd/fork.go, cmd/issue_create.go, cmd/mr_create.go, cmd/snippet_create.go, cmd/util.go, internal/git/git.go, internal/git/git_test.go
This MR doesn't introduce any code behavior change, it only remove some unused code (function and arguments) and rename the function `git.PathWithNameSpace` to `git.PathWithNamespace`.
=> Remove and rename some functions and arguments

Makefile
When using make install, lab would install with version `master`, with
the current change, the version is the same as the one shown on build.
=> Added version to make install

cmd/util.go
Instead of returning an error in case of an unknown number of args, let
it return the nil values and let the caller handle it as it please. For
"mr_note", "issue_note" and "mr_edit" the error was interrumpting the
cmd line argument parser.
Fixes: ecd57aaf4afa ("cmd/util: avoid an empty string to be parsed")
=> cmd/util: fix handle of unknown number of arguments

cmd/issue_note.go, cmd/note_common.go
This MR clean 2 things up:
1) move noteRunFn to cmd/note_common.go file since it's used by both mr_note and issue_note;
2) instead of using `os.Args`, use `cmd.Parent().Name()` and `cmd.CalledAs()` to avoid surprises with `os.Args` being mangled.
=> Move noteRunFn to a common place and fix os.Args usage

cmd/ci_status.go
Per discussion in #240, lets just bump up the interval, totally open to putting it behind a flag, but in the context of waiting for a an entire pipeline to finish, 1s is clearly a bit too aggressive.
=> chore: (ci status) #240 bump up default wait interval

cmd/show_common.go
Output the commid ID hash on commit comments.
Note: The behavior of note.Position.BaseSHA has changed to point to the
commit just before the commented on commit.
=> mr show: Output commit ID hash on commit comments

cmd/mr_create.go
In case the user could use `lab mr create --source` with "remote" only,
without the branch part, or at least using `:` it would panic:
---- 8< ----
panic: runtime error: index out of range [1] with length 1
github.com/zaquestion/lab/cmd.runMRCreate(0x18f3600, 0xc00055a460, 0x0, 0x2)
/home/bmeneg/git/lab/cmd/mr_create.go:125 +0x207e
github.com/spf13/cobra.(*Command).execute(0x18f3600, 0xc00055a440, 0x2, 0x2, 0x18f3600, 0xc00055a440)
/home/bmeneg/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x18f8f40, 0xc00012a000, 0x5, 0x5)
/home/bmeneg/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
/home/bmeneg/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go …
=> cmd/mr_create: fix index out of range with --source

cmd/mr_approve.go, cmd/mr_unapprove.go
Fixed a bug where a comment would be added to an MR on approve or
unapprove, even if the MR was already reviewed by the user.
Changed -m and -f behavior so they don't depend on --with-comment to be
used.
=> Removed --with-comment dependency; Fixed approve bug

cmd/mr_thumb.go
`Thumb Down` cannot determine MR id, changed the function to the same used on `Thumb Up`
=> Fix thumb Down

cmd/todo_done.go
Before that condition, if the user used `lab todo done`, a `runtime
error: index out of range [0] with length 0` would occur.
=> cmd/lab_todo: fix index out of range without any args

cmd/snippet_browse.go
Snippets could not get hostURL from cfg, mimicked the code from
mr_browse.
=> cmd/snippet_browse: Fix Snippets Browse cfg host

internal/config/config.go
Gitlab profile URL must have changed sometime in the past.
Correcting to the new one.
=> Fix gitlab profile link URL

cmd/mr_create.go
MR create shows two references to remote with the --souce option when
there should be just one.
=> Fix MR create documentation

cmd/ci.go, cmd/ci_artifacts.go, cmd/ci_status.go, cmd/ci_trace.go, cmd/ci_view.go, internal/gitlab/gitlab.go
ci: filter jobs by bridge name
When multiple bridg jobs (downstream pipelines) are available in the CI
pipeline of a project, only the information of the last one returned by the
API is shown, ignoring the existence of any other. Bridge jobs have their
own names and lab should give the opportunity to the user filter jobs by
this name.
Filter bridge jobs returned from the API by comparing their name and the
name passed by the user in the cli.
Fixes #725
=> Allow users to specify CI brigde jobs by their name

cmd/mr_create.go
The current help message is a bit confusing about what's target and what's
source remote and branches. The user should not need to guess what we mean.
With that, explicitly state target_remote and target_branch for positional
args and make the examples clearer.
=> mr_create: clarify help wrt source and target remotes and branches

cmd/issue_note.go, cmd/issue_show.go, cmd/mr_approve.go, cmd/mr_discussion.go, cmd/mr_note.go, cmd/mr_show.go, cmd/mr_show_test.go, cmd/mr_unapprove.go, cmd/note_common.go, cmd/show_common.go, internal/git/git.go, internal/gitlab/gitlab.go
The GitLab WebUI allows users to comment directly on commits.  These comments
appear both in the comment view and the MR view.  This functionality can be
implemented via the lab.Commits.PostCommitComment() function, however, the
function only supports comments on "new" lines of code.  After discussions
with GitLab they have suggested using lab.Discussions.CreateCommitDiscussion()
as a workaround [1].  This solution has a minor issue in that it will not work
with commits that have multiple parents
Implement the ability for users to comment directly on commits.
[1] https://gitlab.com/gitlab-org/gitlab/-/issues/335337#note_643291819
=> Add commit comment functionality

cmd/mr_approve.go
This fixes the issue of approval being sent on file error.
Unfortunately, it does not prevent the file comment to be sent on approval error, but since approval errors are less common, I think this would be better than how it is.
I will work in GitLab to comment and approve in one API call.
=> Moved file function to break before approval

cmd/show_common.go
In some cases note.CommitID is not set.  In these cases AFAICT the
note.Position.HeadSHA value does correctly point to the commented on
commit and the rest of the data is correct.
Use the HeadSHA value when the CommitID is not specified.
=> lab: Use HeadSHA value when CommitID is not specified

cmd/show_common.go
When executing 'lab mr block 1369 --commit 7ed5bdfc1e' I hit this panic
this morning:
panic: runtime error: index out of range [1] with length 1
github.com/zaquestion/lab/cmd.displayDiff(0xc0005f9ac0, 0x1f, 0x0, 0x0, 0x1, 0xc00017e1c0, 0x6c)
/home/prarit/git-kernel/github/lab/cmd/show_common.go:73 +0xf45
github.com/zaquestion/lab/cmd.getCommitBody(0xc00012230f, 0x16, 0x7fffb9bdc8c6, 0x28, 0x1179236, 0x4)
/home/prarit/git-kernel/github/lab/cmd/note_common.go:135 +0x1f3
github.com/zaquestion/lab/cmd.glob..func37(0x19f8c60, 0xc00052e7b0, 0x1, 0x3)
/home/prarit/git-kernel/github/lab/cmd/mr_discussion.go:66 +0x7be
Part of the diff for 7ed5bdfc1e added a new file with one line, and
contained:
@@ -0,0 +1 @@
The lab diff code assumes that there are always two sets of …
=> cmd/show_common.go: Fix commenting on new file diffs

cmd/mr_create.go, cmd/mr_create_test.go
A request was made to add an option to open the editor when a file was
specified for the title and description.  Opening the editor would allow
project owners and maintainers to deploy MR templates that could be edited
by the MR submitter.
Add a --file-open_editor/-f option that opens the editor with the file
contents.
Closes #739
Suggested-by: David Arcari <darcari@redhat.com>
=> mr_create: Add -f option to open editor

cmd/mr_create.go
Currently, when the file specified with the -F or -f options does not
exist, lab outputs a very generic error that is not helpful to users
[prarit@prarit kernel-test]$ ~/git-kernel/github/lab/lab mr create
2021/09/22 07:14:40 ERROR: mr_create.go:289: empty MR message
Check to see if the file exists and report a better error if the file is
not present.  For example,
[prarit@prarit kernel-test]$ ~/git-kernel/github/lab/lab mr create -F /tmp/non-existent.file
2021/09/22 07:15:02 ERROR: mr_create.go:244: file /tmp/non-existent.file cannot be found
Fixes #742
=> lab mr create: Check file exists (-F/-f options)

internal/gitlab/gitlab.go
In cases where the number of comments in a certain Issue/MR is greater than
10k the HTTP header for the API responses lack the X-Total and X-Total-Pages
metadata [1] used by lab to control the response pagination. Even though it
should not happen in real scenarios, it's breaking our tests where some MRs
have more than 10k comments. The solution adopted was to use the X-Next-Page
header whenever the X-Total(-Page) is not found.
[1] https://docs.gitlab.com/ee/user/gitlab_com/index.html#pagination-response-headers
=> gitlab: handle API response without X-Total(-Pages) HTTP header

cmd/mr_approve.go, cmd/mr_unapprove.go, cmd/note_common.go
This is the second part of the change to unify the calls made when approving/commenting on an MR.
The new code removes the usage of the `merge_request/approve` API and instead uses the `/approve` and `/unapprove` notes API quick actions.
Fixes: #708
=> Review with quick actions

cmd/ci_run.go, internal/gitlab/gitlab.go
This MR has three different and minor fixes:
1. Remove redundant code in `internal/gitlab/gitlab.go::FindProject()`
2. The `--project` value was being used as the value for `token` variable instead of `--token` value.
Check the individual commits for more information.
=> Remove redundant code and fix flag option

cmd/mr_discussion.go, internal/git/git.go
(the first two commits are independent updates but I included them here to avoid conflicts)
---
GitLab supports to comment on lines (or even ranges of lines) within a
commit diff.  This is standard practise when using the web interface,
and it's arguably friendlier to the MR author.
Add a bunch of --position-* parameters to "lab mr discussion" to implement this [1].
(This interface is awkward, because almost all of them are needed.
Maybe we could fit all of this in one parameter somehow? Then there'd
be less room for user errors.)
Given a commit diff like
--- a/README.md
+++ b/README.md
@@ -3,2 +3,5 @@
line 3
line 4
+line 5
+line 6
+line 7
this allows to run a command like this to comment on "line 6".
lab mr discussion origin branch --commit=commit-id --position-file=README.md …
=> mr discussion: allow to comment on specific lines in a diff

README.md
Clarify the precedence of the environment variables for
authentication.
Add information on `GITLAB_USER_LOGIN` being used in the CI.
Add an example of how to set `LAB_CORE_HOST`
Closes: #767
=> Clarify usage of environment variables for authentication

internal/config/config.go
This can be useful when trying to troubleshoot issues.
=> Add debug level log messages when Gitlab CI tokens are loaded

README.md
Based on #630, it appears that the project no longer wants people to
use lab as a replacement for the git command. So we shouldn't
recommend to people that the do `alias git=lab`.
Update README.md to remove this recommendation.
=> Remove documentation about using lab as a replacement for git

.gitlab-ci.yml, .travis.yml, cmd/root_nowindows_test.go, cmd/root_windows_test.go, cmd/util_bsd.go, go.mod, go.sum
Update go.mod version to take advantage of the latest module graph and
lazy-loading mechanisms in 1.17+
https://go.dev/doc/modules/gomod-ref#go-notes
=> lab: update go.mod version

internal/config/config.go
The config code doesn't follow the worktree git config file when the
user calls for a command that depends on that from within a 
`git worktree` directory. In this cases, the .git path is in fact a file
instead of a valid directory, which turns to point to the actual
worktree configuration dir.
Instead of realying in a hardcoded path (`.git/lab`), make use of the
`git rev-parse --git-dir` command already available in the git commands
code (internal/git/git.go) and which follows the worktree situation.
Fixes #773
=> config: fix worktree git config dir path

cmd/note_common.go, internal/gitlab/gitlab.go
@krobelus noticed that it wasnt possible to comment on the context portion
of a diff.  For example, when commenting on line 6 of
| newfile: Makefile oldfile: Makefile
|        @@ -5,6 +5,8 @@ SUBLEVEL = 0
|  5   5  EXTRAVERSION =
|  6   6  NAME = Merciless Moray
|  7   7
|      8 +# space
|      9 +
|  8  10  #
|  9  11  # DRM backport version
| 10  12  #
it was not possible to comment on line 6 and lab would output an error.
This is fixed by reworking the code to detect context diffs, however, this
only appears to work on code shown before the difflines.  There are
several open GitLab API issues that report errors when commenting on Merge
Request commits and it is likely that one of these is causing the error.
ex) https://gitlab.com/gitlab-org/gitlab-foss/-/issues/28599
Rework the code …
=> cmd/note-common.go: Fix context comments on diffs

cmd/edit_common.go, cmd/edit_common_test.go, cmd/issue_edit.go, cmd/mr_create.go, cmd/mr_edit.go, cmd/root.go, testdata/testedit
While editing an MR or issue description if any flag different from -m and -F is used the editor is not opened. Add the --linebreak to this list of "accepted" flags to be used for editing the description.
Also, this MR bring other lateral fixes and improvements related to code organization, make sure to check each commit separately.
=> Fix flag bypass for editing description

cmd/label_list.go
This adds a new `--name-only` flag to `lab label list` to print the labels w/o descriptions.
Example:
```
❯ lab label list
P1 - High priority
P2 - Medium Priority
P3 - Low priority
...
❯ lab label list --name-only
P1
P2
P3
...
❯ lab label list Type
Type::bug - This is a defect; something that should not be happening.
Type::dev/maintenance - An internal or developer-centric issue.  Think: house cleaning or repair.
Type::discussion - Questions or discussion.
Type::feature - New features or an improvement to existing fuctionality.
Type::operations - Primarily server related. Server, DNS, hosting, etc.
❯ lab label list Type --name-only
Type::bug
Type::dev/maintenance
Type::discussion
Type::feature
Type::operations
```
I did not add a test, but I have been using this for a while. Also, the …
=> label list: add `--name-only` flag

cmd/mr_checkout.go, cmd/mr_checkout_test.go, internal/git/git.go
In case tacking is enabled `lab mr checkout -t`, a new remote is created
with the name of the MR author's name without checking if the already
available remotes matches the one from which the MR was checked-out.
A particular case where it happens constantly is in the branching
development model: developers use a single repo to push their work as
branches.
This patch change the code behavor by first checking if any of the
existent remotes has the same path as the source MR project before
creating a new remote. If no remote is found, then create a new one with
the MR author's name.
Related: #774
=> cmd/mr_checkout: check existing remotes before creating one

cmd/project_create.go, cmd/project_create_test.go, internal/gitlab/gitlab.go
The group search logic didn't consider the fact that the GitLab API
returns an alphabetical ordered list of groups within a certain group,
thus when multiple subgroups were nested the value groups[0] and list[0]
used in the code weren't always the expected ones.
With that, instead of looking up for the first group, we look for the
last one, meaning that all subgroups found in user's namespace or
wherever he has access to, is returned from the API. The match then
happens with the group full path or full name, which matches first.
In case the user has access to multiple groups with ambiguous names,
all possible paths are shown and lab's exits.
Also, a new flag `--remote` was added to allow the user to provide a
remote name in case needed. `lab` don't add a remote by default.
Related: #782
=> project_create: fix group lookup and allow custom remote name

internal/gitlab/gitlab.go
None of the internal/API user's information (host, user, token) were
being set when a custom CA file was set in the cofiguration file. This
patch set them the same way as the Init() function.
Related: #787
=> internal/gitlab: fix init with custom CA file

cmd/fork.go, cmd/root.go, internal/gitlab/gitlab.go
This patch is mostly a standardization of the project ID used in our internal gitlab module, which is a complete mix of interface{} and string with no real reason for that. We don't have any issues with it because the go-gitlab module does accept interface{} and handles the data conversion internally, however, the lack of standard can be confusing sometimes for us lab developers.
To help achieving it the fork command had to be support interface{}, and thus enabled the ability to the user pass the project ID instead of only the project name.
=> Unify project ID type across lab's internal gitlab module

cmd/issue_edit.go, cmd/mr_edit.go
When --force-linebreak is set through the config file the conditional
for opening the editor will always be satisfied no matter what's the
other flag being used together, since it only requires NFlag() == 1 and
linebreak being set.
For instance:
lab.toml:
[mr_edit]
force-linebreak = true
cli:
$ lab mr edit --ready
[EDITOR IS OPENED]
This patch fixes it by checking it linebreak is being actually set
through the CLI, so in case NFlag() == 1 we're sure the user wants to
open the editor considering the "force-linebreak".
Related: #790
=> cmd/edit: check if --force-linebreak coming from CLI or config

cmd/ci_run.go, cmd/mr_create.go, cmd/util.go, cmd/util_test.go, go.mod, go.sum, internal/git/git.go, internal/git/git_test.go
When using git-push the user can set the upstream of a branch to a
remote that is not present in the current repository by referring to its
URL. In these cases, git checks for the validity of the URL itself
instead of checking if a remote with that name exists locally.
I.e.:
```
$ git push --set-upstream <URL>
```
This case affects lab mostly when we use the remote URL to lookup for it
in GitLab: lab checks for the branch's remote name.
`branch.<branch>.remote`, then it gets the remote URL itself; however,
in this situation, the `branch.<branch>.remote` will be the URL already
and any check for that remote in the local repository fails.
The biggest problem is the amount of different URL formats supported by
Git [1], which is bigger than the ones supported by the usual
url.Parse() (net/url …
=> remote: support remotes referred by URL only

cmd/mr_create.go
Currently lab outputs this error when an unknown project is found:
"GitLab project not found, verify you have access to the requested
resource".
While this error does match the webUI, it doesn't provide enough
information to debug the error.  The webUI in this case still provides
the name of the unknown project where lab only outputs the generic
warning.
Update the "Project Not Found" error with the unknown project name.
=> lab: Provide a better "Project Not Found" error message

cmd/issue_edit.go, cmd/issue_edit_test.go, cmd/mr_edit.go, cmd/mr_edit_test.go, internal/gitlab/gitlab.go
Add the ability to delete notes from issues and MRs with the --deletenote
option.
=> lab: Add MR and Issue note delete functionality

cmd/issue.go
The 'issue' command is one of the high-demand commands within lab with,
probably, 'mr', and enabling the alias 'i' for it seems a good approach
for all lazy developers that we all are. 'mr', 'todo', 'ci', 'repo' are
already shorthand themselves, adding this specific to 'issue' should not
harm, even more considering we aren't creating one-letter aliases to
every single command.
Fix #810 .
=> cmd/issue: add "i" alias to the command

README.md
In order to make the README information more clear this patch overhaul
its structure and update its content to match the current state of the
tool.
Fix #777 .
This PR semantically depends on PR #809 being merged, otherwise some recommendations won't work as expected.
=> README: overhaul file structure

cmd/root_test.go
A random usigned interger is used for generating the testdata directory
name, but an int() casting is done right after and, because of that,
depending on the size of the generated uint, the int casting will make it a
negative number. Consequently, the negative sign is maintained in the
resulting string from the strconv.Itoa() conversion, leading to a directory
name with two dashes: "testdata--8339364144815363225".
Even though this name format isn't a problem to lab itself, it's used as
"project name" for the project_create command testing code, which isn't
supported by GitLab:
ERROR: project_create.go:94: POST https://gitlab.com/api/v4/projects: 400
{message: {path: [must not start or end with a special character and must
not contain consecutive special characters.]}}
This patch format …
=> project_create_test: fix negative sign on testdata dir name

cmd/mr_create.go, internal/git/edit.go, internal/git/edit_test.go
The default behavior when creating an MR is to open the editor regardless
the amount of commits:
- 1 commit: open editor with the commit's title and body already in place.
- 1+ commits: open editor with an empty message
This patch adds the --no-edit to allow users of the first option (single
commit) to tell lab to create the MR using the commit's message right away,
without opening the editor.
If --no-edit is used with the second option (multiple commits) lab exits
with a error message.
Fixes #819 
=> cmd/mr_create: add --no-edit flag to not open editor

cmd/util.go
'lab mr create -a <username>' panics if someone specifies a username that
doesn't exist:
[prarit@prarit kernel-test]$ ~/Other/github/lab/lab mr create -a prarit123456
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc942b8]
github.com/zaquestion/lab/cmd.getUserIDs(0xc000242420, 0x1, 0x1, 0xc000034700, 0x0, 0x0)
/home/prarit/Other/github/lab/cmd/util.go:662 +0x98
github.com/zaquestion/lab/cmd.runMRCreate(0x14a2940, 0xc0000fe540, 0x0, 0x2)
/home/prarit/Other/github/lab/cmd/mr_create.go:347 +0x10e9
github.com/spf13/cobra.(*Command).execute(0x14a2940, 0xc0000fe520, 0x2, 0x2, 0x14a2940, 0xc0000fe520)
/home/prarit/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2 …
=> cmd/util.go: Fix panic with getUserIDs

cmd/mr_create_test.go, cmd/mr_list_test.go, cmd/mr_show_test.go, cmd/mr_test.go, cmd/project_create_test.go, cmd/snippet_list_test.go, cmd/util.go, internal/gitlab/gitlab.go
This PR fixes the lab's "guess" operation for retrieving the MR ID
based on the currently checked-out branch, which was, recently,
causing issues with the testing code.
Currently, if any MR opened from a forked project but with the 
same source branch name will get mixed with MRs from the 
original project with that name, possibly returning the wrong
ID to the user.
Check the second commit for more detailed information.
=> Fix guessing the MR ID based on the current branch

.goreleaser.yml
On previous commits lab stopped to wrap git commands, thus the homebrew
test needed to be fixed in the point where a call to `lab ls-files` was
being made. At the same time, the whole test doesn't make sense
considering lab wasn't really being used. So, instead of only fixing the
`ls-files` portion, this patch is changing the test to only check the
lab version.
Fixes #833.
=> goreleaser: fix homebrew test case

cmd/mr_browse_test.go, cmd/util.go, internal/gitlab/gitlab.go
When trying to guess the merge request that corresponds to a
local branch, we search for MRs that match the (upstream) branch
name.
But as branch names only have to be unique within a project, it
is possible that there are multiple merge requests from different
forks that use the same source branch name.
Luckily we do know which is the correct source project: It's the
one that corresponds to the remote that the local branch was pushed
to.
=> Consider branch remote when guessing MR

.travis.yml
We're reaching the limit of 10min tests on Travis. This patch increases
the default 10min to explicit 20min.
=> travis: increase timeout limit

.gitignore
The previous commit added the `travis_wait 20` to the `make test`
command on travis yml file, however, this command generates a .log file
that polutes the git file system and makes goreleaser to finish its job
due to "dirty git repo". This patch is fixing it by adding the
travis_wait log file to .gitignore as suggested by goreleaser doc [1].
[1] https://goreleaser.com/errors/dirty
=> travis: add travis_wait log file to gitignore

main.go
Tab completing `lab` causes it to try and load the config, which fails if it hasn't been initialised yet, causing it to produce an error and fail to show any completions. This is because the completion invokes `lab _carapace`, which wasn't correctly detected by `skipInit`.
=> Don't load config during shell completion

cmd/issue_browse.go, cmd/issue_browse_test.go, cmd/issue_note_test.go, cmd/mr_browse.go, cmd/mr_browse_test.go, cmd/mr_discussion_test.go, cmd/mr_note_test.go, cmd/mr_test.go, cmd/snippet_browse.go, cmd/snippet_browse_test.go, internal/gitlab/gitlab.go
Like #855, this also deals with a breaking change in GL 16.0. In this case, support for "legacy" URLs has been removed, and this is also breaking `lab issue browse`, `... mr browse`, and `... snippet browse`. This change should update all of these so that they work again.
**BREAKING**
As I understand it, these delimited URLs should work on any version of GL since v9 (2017) but these changes will bread the browse commands for users of older versions. If this is a concern, I suppose we could use a config flag to control the URL format.
**FMI** 
Deprecation notice: https://docs.gitlab.com/ee/update/deprecations.html?removal_milestone=16.0#legacy-urls-replaced-or-removed
List of affected URLs: https://gitlab.com/gitlab-org/gitlab/-/issues/28848#release-notes
=> fix(browse): Update browse URLs

cmd/token.go, cmd/token_create.go, cmd/token_list.go, cmd/token_revoke.go, cmd/token_show.go, cmd/util.go, internal/gitlab/gitlab.go
Add support for showing the current token, listing all of a user's tokens, revoking tokens, and creating tokens (creating tokens is limited by the GitLab API to Administrator level only).
=> lab: Add token support

cmd/token.go
Trivial change to bring `lab token` in line w/ other commands when called w/ no subcommand is given on CLI.
@prarit nice work on the `token` command, BTW
=> fix(token): Show help when no subcommand given

cmd/token_test.go
Add token command testing for create, list, and revoke.  This is best done in a single test where a token is created, listed, and then revoked.
=> cmd/token_test.go: Add testing

cmd/project_browse.go, cmd/project_browse_test.go
@sding3 has requested the ability to browse to a specific file using a --file argument.  In addition to this I think it is a good idea to also add a --branch argument so users can browse a file on a specific branch.
Add --file and --branch options.
Close #866
=> cmd/project_browse.go: Add --file and --branch options

cmd/mr_create.go
The -f option was reported to be broken.  This occurred due to a coding error and this simple change will fix it.
Fix the -f option (-F and no options have also been verified to work).
=> cmd/mr_create.go: Fix -f option

cmd/project_browse.go, cmd/project_browse_test.go
This updates amends #869 by removing the `--branch` option, allowing the `--ref` option to be able to take in git branch, tag, or SHA. This updates also makes the `--ref` option orthogonal to the `--file`.
To test this update, target the [zaquestion/test repo hosted on gitlab](https://gitlab.com/zaquestion/test/-/tree/master) with various command invocations:
```
lab project browse
lab project browse --ref master
lab project browse --ref v0.1
lab project browse --ref 63cce1d0
lab project browse --ref master --file .gitlab-ci.yml
lab project browse --ref v0.1 --file .gitlab-ci.yml
lab project browse --ref 63cce1d0 --file .gitlab-ci.yml
```
=> remove --branch on project browse command, as it is redundant with --ref

cmd/root_test.go, internal/gitlab/gitlab.go, internal/gitlab/gitlab_test.go, main.go
Lab previously would appear to be hung if a gitlab API request is in-flight and the user wants to cancel the command with control-C. Now we set up a context whose cancellation is tied to `os.Interrupt` and this context is used in API requests with gitlab.
Lab previously ignored error in loading custom CA cert. Now that error is bubbled back into main and reported back to the user.
=> constrain gitlab API calls with context

README.md
- Update scoop installation note.
Since available and regularly updated in scoop's `main` bucket (originally added as ScoopInstaller/Main#422), `lab` can be installed without adding additional buckets.
- Minor formatting enhancements across README.
=> docs: update scoop installation note

cmd/milestone_browse.go, cmd/milestone_browse_test.go, cmd/milestone_create.go
This adds a couple things to `lab milestone`:
- `milestone create` now accepts flags `--start` and `--due` to set the respective dates for the new milestone
- GL API docs: https://docs.gitlab.com/ee/api/milestones.html#create-new-milestone
- `go-gitlab` docs: https://pkg.go.dev/github.com/xanzy/go-gitlab#CreateMilestoneOptions
- does *not* add tests for this because there is no test coverage for `milestone create` anyway
- I have tested it manually and it worked as expected
- date parse code was largely copied from `CreatePAT` in `internal/gitlab/gitlab.go`
- Adds a new `milestone browse` subcommand
- unlike `issue/mr/snippet browse`, which all accept an `id` for a specific resource, `milestone browse` takes the name of a milestone
- maybe it's just me, but I did this because I never …
=> feat(milestone): Add `--start` & `--due` to `create`; Add `browse` subcommand

cmd/ci_status.go
'lab ci status' shows status for each job as well as each pipeline.  There are various states (success, failed, skipped, etc.) that can be output.
Currently the output is in white.  It would be nice if these were easier to read in color: red for failed, green for success, and yellow for the various 'in progress' states.
Output the ci status in color.
=> cmd/ci_status.go: Add color to ci status output

cmd/mr_show.go
There are three statuses that affect the overall status of a merge request.  The first is the general status (open, closed, or merged), the CI status (in progress, successful, failure) and lastly a 'detailed' status which provides information like 'not approved' or 'ci_must_pass'.
Output all Statuses in color.
=> Update status output

cmd/mr_show.go
Running 'lab mr show --comments' on an issue with no pipeline results in
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xecaa34]
github.com/zaquestion/lab/cmd.printMR(0xc000618008, {0xc00004132f, 0x18}, 0x1)
/home/prarit/Other/github/lab/cmd/mr_show.go:256 +0xd74
github.com/zaquestion/lab/cmd.init.func63(0x1a31ee0, {0xc000694860, 0x1, 0x10e5b6f?})
/home/prarit/Other/github/lab/cmd/mr_show.go:82 +0x3c9
github.com/spf13/cobra.(*Command).execute(0x1a31ee0, {0xc000694840, 0x2, 0x2})
/home/prarit/Other/github/lab/vendor/github.com/spf13/cobra/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x1a26400)
/home/prarit/Other/github/lab/vendor/github.com/spf13/cobra/command.g …
=> cmd/mr_show.go: Fix null pipeline error

cmd/mr_list.go, go.mod, go.sum, internal/gitlab/gitlab.go
I've always found the project merge_requests page useful.  It shows the
status of MRs, the CI and Approval statuses, etc.  Let's start doing that
in the 'mr list' command.  I still like the default simple command, so
let's add a '--show-state' to get fancy output.
Note, that this requires a per-MR lookup to get the CI status.  That
slows the output of --show-state down, but it's worth the trade off.
Add --show-state to output similar to the project merge_requests page.
=> Add mr list fancy
